### ISSUE TITLE
Multitouch gesture support

### ISSUE THREAD

**Issue by altaic** [atom-haskell/ide-haskell#100]
Sometimes type/info is not available for one reason or another, and I find myself hovering and re-hovering to no avail (not to mention sometimes info is popping up all over the place when I don't want it to). It would be excellent to be able to use multitouch gestures in ide-haskell for things like type/info popups, a la 3 finger taps for info lookups on OS X.

After some searching, I came across [atom-touch-events](https://github.com/russlescai/atom-touch-events), though I'm not sure what system events it manages to capture. Might be worth looking into a bit more.

**Comment by altaic** [comment]
I hacked together simple support by adding the following to `editor-control.coffee` @ line 72:
```coffeescript
    # gesture support for three-finger tap
    @disposables.add @editorElement, 'touchend', '.scroll-view', (e) =>
      return if e.originalEvent.targetTouches.length != 3

      @lastMouseBufferPt = bufferPositionFromMouseEvent @editor, e

      action = atom.config.get('ide-haskell.onThreeFingerTap')
      return if action == 'Nothing'

      @showExpressionType bufferPt, 'mouse', 'get' + action
```

and the following to `ide-haskell.coffee` @ line 48:
```coffeescript
    onThreeFingerTap:
      type: 'string'
      default: 'Type'
      enum: ['Nothing', 'Type', 'Info']
```

and, finally, the following to my `config.cson` under `"ide-haskell":`
```coffeescript
    onThreeFingerTap: "Info"
```
... which unfortunately did not work. Touch events are currently only issued on mobile devices and not for trackpad gestures. The root of this issue is upstream and, sadly, not getting much attention: https://github.com/atom/electron/issues/1486

**Comment by lierdakil** [comment]
Consider using keyboard shortcuts or context menu. I personally use
keyboard, and it works out great for me. There's not much I can do without
upstream support.
10 сент. 2015 г. 11:49 пользователь "altaic" <notifications@github.com>
написал:
