### ISSUE TITLE
Use Type as fallback when Info not available

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell#103]
I'd prefer to see the full info instead of only type, but that currently means lots of objects that *can* show type just show an error icon in the panel and no tooltip. I'd prefer to show maximum info on hover generally, i.e. show Info when available and otherwise show Type.

**Comment by lierdakil** [comment]
Sounds reasonable. I'll see what I can do.

**Comment by lierdakil** [comment]
So, I have implemented this, but for it to work properly, it needs changes from https://github.com/atom-haskell/ide-haskell/pull/91, and it's blocked by atom/atom#8313. So no-go until latter is fixed (there is actually a PR pending, but those get merged quite slowly right now...)

**Comment by lierdakil** [comment]
Available in 0.8.0.
