### ISSUE TITLE
Scrollbar rendering does not obey theming

### ISSUE THREAD

**Issue by fgrsnau** [atom-haskell/ide-haskell#104]
When I fire up Atom the scrollbar in the error pane looks weird. This is not a big problem, but the very large scrollbar is a little bit distracting. :-) Here is a screenshot showing the problem:

![shot](https://cloud.githubusercontent.com/assets/11267323/9851877/2131ea06-5af3-11e5-8cac-a1113f1bb94e.png)

I had a closer look and it seems like the CSS properties of the theme are applied correctly. Atom still renders unthemed scrollbars.

![shot](https://cloud.githubusercontent.com/assets/11267323/9851950/8bfdbaa4-5af3-11e5-978d-b8698018f805.png)

If I toggle the property “overflow-y: scroll;” of the selector “.ide-haskell-panel .panel-body” off and on again, the scrollbars are rendered correctly!

After some trial and error I figured that [changing this line](https://github.com/atom-haskell/ide-haskell/blob/2b193db8f07a83bb8ef342be5823d64fc191c2c0/styles/ide-haskell.less#L76) to “overflow-y: auto;” somehow solves the problem. Nevertheless, this does not make any sense to me.

![shot](https://cloud.githubusercontent.com/assets/11267323/9852105/4bee2a7e-5af4-11e5-95e0-75dd9a81b6d5.png)

I have never hacked on Atom before, so I have no idea what’s causing this issue and whether my “fix” is reasonable. Maybe someone can leave a comment.

**Comment by lierdakil** [comment]
Um. This seems like rendering engine bug at a first glance. Would you mind specifying your OS and Atom version?

**Comment by fgrsnau** [comment]
Oh, sorry. I’m using Atom v1.0.11 on Arch Linux.

**Comment by lierdakil** [comment]
Okay, so I tried to reproduce this with various Atom versions on Gentoo Linux, and couldn't, so I have literally zero ideas on what's wrong here. If you're still experiencing this problem on Atom 1.0.15 or above, please write back and I will adjust stylesheet as you outlined in OP. Thanks.

**Comment by fgrsnau** [comment]
The problem is still present in Atom version 1.016.

For the record, I enabled `* { overflow: scroll; }` in my user stylesheet (which looks, of course, pretty strange). All but ide-haskell’s scrollbars are rendered correctly.

If you don’t want to modify the stylesheet, affected users (maybe it’s just me) can simply put this snippet into their own style file:

    .ide-haskell-panel .panel-body {
	    overflow-y: auto;
    }

This magically resolves the issue and the scrollbar is only rendered when needed.

**Comment by lierdakil** [comment]
Okay, using `overflow-y: auto` in v0.8.0. Hopefully this works.
