### ISSUE TITLE
option to turn on GHC-mod only when desired

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell#106]
I really dislike how opening haskell files in atom now necessarily runs ghc-mod. I'd like a setting where it is off by default until I choose to turn it on.

**Comment by lierdakil** [comment]
Actually, it shouldn't run until ide-haskell asks for type/info or autocomplete-haskell collects information on modules or needs type for completions. So disabling type/info on mouseover should be an option. I really don't want to complicate settings unnecessarily.

**Comment by wolftune** [comment]
I'll try the latest and see if it works. Even when I have my mouse not on Atom at all, it seems to run right upon starting when the file open from before was a Haskell file, but I'll see how the update is

**Comment by lierdakil** [comment]
Let's make one thing clear: autocomplete-haskell tries to cache module information as soon as you open a Haskell file (otherwise, you might need to wait for quite some time before first completion suggestion pops up). But those ghc-mod processes are relatively short-lived and should end in a minute or so.

**Comment by wolftune** [comment]
Oh, that makes sense! I suppose my request is really for autocomplete-haskell to offer to turn off auto-caching and only cache after the first time it's called. But I don't know for sure if I'd end up preferring that after really using it.

**Comment by lierdakil** [comment]
I'm not keen on this request. For modules with little imports, this doesn't really make that huge of a difference in any case. But if there are quite a bit of imports (say, 10 or more), then you might have to wait for a minute and then some until autocomplete-haskell indexes all imports and presents you with autocompletion hints. If you have 'show completions on keystroke' enabled (that's the default I believe), this is definitely *not* something you want, and even if you don't, it gets annoying *really* fast to say the least.

**Comment by wolftune** [comment]
ok, thanks for clarifying
