### ISSUE TITLE
Jump to definition implementation.

### ISSUE THREAD

**Issue by malarkannan** [atom-haskell/ide-haskell#110]
I noticed it is in the list of TODOs and even though  [Ariadne](https://github.com/feuerbach/ariadne) is unmaintained it might be a good place to start.

**Comment by nicolasazrak** [comment]
it would be really nice if I was implemented with https://atom.io/packages/hyperclick

**Comment by lierdakil** [comment]
@malarkannan, I have a general idea on how to implement this, but due to time constraints wasn't able to start hacking. So all in all, ariadne wouldn't really help much. Thanks for your interest though.

@nicolasazrak, thanks, I will keep this in mind.

**Comment by bfly2000** [comment]
Hi, I ended up implementing this as a backend provided service in a fork, along with my stack-ide backend. should i create PR for the ide-haskell portion?

**Comment by lierdakil** [comment]
So, I tried hyperclick, and apparently it doesn't work that well either with Atom 1.3.2, or with Haskell sources, so this is no-go.

Go-to-declaration is implemented by haskell-ghc-mod (more accurate, but doesn't work for symbols that are not exported) and ide-haskell-hasktags (less accurate, but works for all top-level symbols). Latter overrides symbols-view package for a similar experience.

**Comment by lierdakil** [comment]
@bfly2000, sorry about lack of reply, I somehow missed your message. I think API has changed drastically since, so I'm not entirely sure if it's still viable, but I'd be interested in at least looking at your implementation of stack backend.
