### ISSUE TITLE
Do not detect -Werror notice as error

### ISSUE THREAD

**Issue by cblp** [atom-haskell/ide-haskell#111]
Do not write
```
.../Dummy: 0, 0
Failing due to -Werror.
```
to error pane.

Do not auto-switch to errors pane when only "error" is the "-Werror" notice, because the real interest is in the warnings pane.

**Comment by lierdakil** [comment]
What versions of ghc-mod and ghc do you run? With `-Werror`, warnings *are* displayed in error pane for me.

**Comment by cblp** [comment]
The Glorious Glasgow Haskell Compilation System, version 7.10.2
ghc-mod version 5.4.0.0 compiled by GHC 7.10.2

**Comment by cblp** [comment]
I've installed it with `stack install cabal-helper ghc-mod`.

**Comment by lierdakil** [comment]
That's... strange. I have literally the same versions installed, but apparently get different behavior. Anyway... filtering out 'Failing due to -Werror' shouldn't be too hard, but I'm kinda reluctant to do it, since this can be valuable information in some cases, *especially* if warnings end up in 'Warnings' pane.

**Comment by cblp** [comment]
One of updates fixed the problem. I didn't notice which one.

Thank you.

**Comment by cblp** [comment]
For clarity: now, if warnings are treated as errors by the compiler (`-Werror` option), they are also shown in the errors pane in editor, so user don't have to switch to warnings pane each time to see them.

**Comment by cblp** [comment]
Никогда такого не было, и вот опять.

With `-Werror` I get warnings in Warning pane, but focus every time automatically switches to Error pane, where I see useless
```
.../test/Main.hs: 0, 0

.../Dummy: 0, 0
  Failing due to -Werror.
```

Please notice
1. The error message for Main.hs is empty.
2. When I run `ghc-mod check` from command line, I get the same warnings and error on `Dummy:0:0`, but without Main.hs. Where does it come from?

**Comment by lierdakil** [comment]
Okay, so 1.10.2 filters out 'Dummy' messages and shows those as notifications.

I have no idea where that `Main.hs: 0, 0` comes from. You could enable debug mode in haskell-ghc-mod settings and try to find that out yourself.

**Comment by cblp** [comment]
I hacked my own copy ghc-mod to make it suppress `Dummy` message, so it printed empty line instead of that, and Atom showed me two messages about `Main.hs: 0, 0`. I think the first one is from some false empty line, too.

**Comment by lierdakil** [comment]
1.10.3 should filter out empty lines and the like.

**Comment by cblp** [comment]
Thank you! I'll try it soon.

**Comment by cblp** [comment]
haskell-ghc-mod@1.11.0 works good! thank you!
