### ISSUE TITLE
add support for HaRe

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell#112]
This would go massively toward making ide-haskell a full IDE:

https://hackage.haskell.org/package/HaRe — complete refactoring tool, like instantly change the name of anything and move definitions around and more

Unfortunately, it will never work with GHC 7.8 but it could be enabled for GHC 7.10+

**Comment by lierdakil** [comment]
We'll see what we can do. Not much time these days.

**Comment by lierdakil** [comment]
Looking at how my time is already stretched thin over atom-haskell projects, I think I will add a 'help wanted' label here.

Anyone willing can start on a package for HaRe support -- I will be happy to co-maintain and endorse it. Personally, don't see much reason in building HaRe support upon existing ide-haskell packages.
