### ISSUE TITLE
Error/Warning/Lints not showing

### ISSUE THREAD

**Issue by jannickj** [atom-haskell/ide-haskell#117]
Hi so I installed the newest version and now my menu bar doesn't show the errors/warning/lints anymore.

I tried to run ghc-mod check Main.hs
and that worked just fine, but in the console with debug it says it runs:
haskell-ghc-mod debug: running C:\Users\jaj\AppData\Roaming\cabal\bin\ghc-mod.exe browse,-d,Main with options.cwd = C:\Users\jaj\Projects\haskell\mongo,options.env = [object Object]
which returns "ghc-mod: unknown command: `browse,-d,Main'" when i run it in the cmd

one thing to note as well is that mouse over types works just fine.

Versions:
Windows 8.1
ghc 7.10.2
cabal version 1.22.4.0
ghc-mod 5.4
ide-haskell 0.8
haskell-ghc-mod 0.9.13
language-haskell 1.4.11

**Comment by lierdakil** [comment]
Okay, not exactly sure what you mean. Menu bar? Why is browse relevant?
You'll have to explain in more detail what you do, what happens, and what
you expect to  happen. Sorry.

I'm pretty sure that 0.8 works adequately.
21 окт. 2015 г. 14:04 пользователь "jannickj" <notifications@github.com>
написал:

**Comment by jannickj** [comment]
Sorry I mean the ide-haskell bar at the bottom, which displays all the Errors/warnings/lints in the tabs. Those aren't showing when I do a check.

**Comment by jannickj** [comment]
My bad, i think the issue is with ghc-mod, so never mind :P
