### ISSUE TITLE
Save and compile haskell projects on-the-fly

### ISSUE THREAD

**Issue by TerrorJack** [atom-haskell/ide-haskell#118]
It would be wonderful if ide-haskell saves the file and invokes the compile process to gather error/lint information whenever the current file is changed. This is the default behavior in Leksah, and currently in ide-haskell this is done only when the file is saved.

**Comment by lierdakil** [comment]
This is doable, but checking can take quite a while on larger projects, even when using ghc-mod's interactive interface. Consequently, user experience can vary wildly depending on project size.
I can add this as an option, but that would be disabled by default, and I'm not convinced in its usability.

**Comment by lierdakil** [comment]
So, okay, I managed to do something, which is available in v1.1.0 of ide-haskell and haskell-ghc-mod (please, update both -- some API changes were needed). As I said, haskell-ghc-mod options 'On Change Check/Lint' are disabled by default.

Note that this does *not* compile projects, only typechecks currently modified buffer (and its imports). This won't catch errors in files that import current buffer.
