### ISSUE TITLE
Bug: Type/Info tooltip don't appear (but backend works normally)

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#119]
Hello, Type/Info tooltip don't appear (but backend works normally)

#### bug

![image](https://cloud.githubusercontent.com/assets/2150990/10787226/6c63c30c-7d6f-11e5-9996-a9280ce96397.png)

#### my packages

![image](https://cloud.githubusercontent.com/assets/2150990/10787252/a741507a-7d6f-11e5-9c00-e2c8c4272dfb.png)

#### ide-haskell config

![image](https://cloud.githubusercontent.com/assets/2150990/10787270/dd373f46-7d6f-11e5-856d-975b17992f20.png)

#### haskell-ghc-mod config

![image](https://cloud.githubusercontent.com/assets/2150990/10787276/f5e80c82-7d6f-11e5-845c-57b91807b4e7.png)

ping @lierdakil

**Comment by rvion** [comment]
indeed, it seems to work with ghc-mod

**Comment by lierdakil** [comment]
Long story short, while fixing a theoretical bug in ghc-modi handling, I've introduced a very practical one. haskell-ghc-mod 1.1.1 *should* work. Can't verify that right now though (no ghc at hand), so if you could, that'd be great.

**Comment by rvion** [comment]
:+1: works perfectly, thanks !

**Comment by rvion** [comment]
@lierdakil by the way, how does it know that I use stack ?

**Comment by lierdakil** [comment]
Later ghc-mod versions added support for stack. There are some caveats, see [ghc-mod wiki for details](https://github.com/kazu-yamamoto/ghc-mod/wiki)

**Comment by rvion** [comment]
thanks again
