### ISSUE TITLE
Error and Lint tooltips don't appear when cursor on mark -  only when mouse over

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#120]
Error and Lint tooltips don't appear when the cursor on mark
It only works when I put the mouse over

Cursor is here but tooltip is not shown

![image](https://cloud.githubusercontent.com/assets/2150990/10787498/9e414848-7d71-11e5-88a3-ec624909b531.png)

when I put the mouse over, or over the mark in the gutter, it works:

![image](https://cloud.githubusercontent.com/assets/2150990/10787507/b9a75aa0-7d71-11e5-80c0-1dddb095310d.png)

ping @lierdakil

**Comment by lierdakil** [comment]
I don't think those ever worked as you describe. Besides, I'm not sure it would be a good idea. Messages can be *long*, so showing those on cursor move seems suboptimal, I think?

**Comment by rvion** [comment]
I probably got used to this behaviour on an other language ide plugin :)

But I remembrer it was surprisingly pleasant.
The mark is only 1 character wide, and you had to get the cursor just before for the tooltip to appear.

I really think (but may be wrong) that it would improve the user experience (especially for lints).
We would no longer need to use the mouse or the bottom panel to review things.

**Comment by lierdakil** [comment]
I've released 1.2.0, which should do something like you described. You need to turn it on in ide-haskell settings, it's off by default.

**Comment by rvion** [comment]
thank you very much
