### ISSUE TITLE
add support for putting the compilation results in a side pane

### ISSUE THREAD

**Issue by haldean** [atom-haskell/ide-haskell#121]
I'm not sure if this is possible, being relatively new to Atom, but it would be awesome if the area that contains the compilation results could be docked to the side rather than the bottom. Developing on a laptop, I have much more horizontal than vertical space to work with -- it's hard to flip back and forth between code and compilation errors when they compete for space so much.

Thanks for an otherwise-incredible development environment!

**Comment by lierdakil** [comment]
Try ide-haskell 1.3.0, it should have what you requested (check ide-haskell settings)

**Comment by haldean** [comment]
This is fantastic, thanks so much!
