### ISSUE TITLE
Errors when import some libraries

### ISSUE THREAD

**Issue by welf** [atom-haskell/ide-haskell#122]
When I try to import Data.List.Extra or Data.Tuple.Extra, I get an error, but if I ignore this error, I can load file in GHCi and mentioned libraries are importing without problems: 

```
Could not find module `Data.List.Extra'
Use -v to see a list of the files searched for. 
```
OSX El Capitan 10.11.1
Atom 1.1.0
ide-haskell 1.3.1
haskell-ghc-mod 1.1.2

**Comment by lierdakil** [comment]
As a wild guess, probably misconfigured cabal file (if any). Can't help much without more knowledge on your setup.

**Comment by welf** [comment]
Может, по-русски? (if you want read it it in english, tell about it pls) Я использую этот файл для того, чтобы делать упражнения из учебников по Haskell, так что он просто хранится на рабочем столе, я для него не заводил отдельного проекта, и, соответственно, он не обращается ни к какому cabal-файлу. Другие модули импортируются без проблем, а вот по этим выдаёт ошибку. Как я уже писал, при этом файл прекрасно компилируется и загружается в GHCi, так что проблема здесь только в том, что сообщение об ошибке создаёт лишний информационный шум в редакторе. 

Я использую не Haskell Platform, а stack, соответственно, ghc-mod и другие библиотеки установлены в глобальный stack.

**Comment by lierdakil** [comment]
Вообще, мое личное мнение, что на англоязычном трекере общаться не по-английски -- дурной тон. Но в общем такие предложения: 1) попробовать засунуть этот файл в другую директорию. Есть вариант, что он цепляет *.cabal-файл из вышележащей (если он там есть) 2) попробовать вручную прогнать `ghc-mod check file.hs` и посмотреть на вывод

English version:
1. Try moving your haskell file, it's possible that ide-haskell grabs *.cabal file from a parent directory.
2. Try running `ghc-mod check yourfile.hs` and see if it outputs the same error or not.

**Comment by welf** [comment]
1. There are no .cabal files neither in the Desktop, nor in the parent directory. 

2. `ghc-mod check File.hs` doesn't output errors.

**Comment by lierdakil** [comment]
Okay, so this is likely an environment issue then.

Please enable 'Debug' option in `haskell-ghc-mod` settings, restart Atom, reproduce this issue, then post developer console contents here (`View` → `Developer` → `Toggle Developer Tools` menu item).

Thanks.

**Comment by welf** [comment]
Here it is. Thanks! 

[-1447626013316.txt](https://github.com/atom-haskell/ide-haskell/files/35042/-1447626013316.txt)

**Comment by lierdakil** [comment]
As I said in https://github.com/atom-haskell/haskell-ghc-mod/issues/65, I'm confused about your PATH settings. `/Users/AW/.stack/programs/x86_64-osx/ghc-7.10.2/lib/ghc-7.10.2/bin/ghc` this doesn't seem like a directory name?..

Besides, I would assume your terminal PATH differs from what ghc-mod gets from Atom. A quick check would be to run Atom from terminal and see if anything changes. Make sure to sort out `additionalPathDirectories` setting first though.

Sorry about prolonged silence, btw, I was a little short on time lately. Thanks for your patience.

**Comment by welf** [comment]
After I made changes described [here] (https://github.com/atom-haskell/haskell-ghc-mod/issues/65#issuecomment-157727384), I started to receive more informative errors about import: 

<img width="606" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1454462/11243715/9c2b86a4-8e1a-11e5-9e17-c95f6de47c63.png">

After I've added [`extra package`] (http://haddock.stackage.org/lts-3.14/extra-1.4.2/index.html) to `build-depends` in project's `cabal` file, the problem was solved. 

Thank you very much!

**Comment by lierdakil** [comment]
Glad to hear that!
