### ISSUE TITLE
Frequent wakeups from idle

### ISSUE THREAD

**Issue by spencerjanssen** [atom-haskell/ide-haskell#123]
On my Linux system, when ide-haskell is enabled and a Haskell file is open, I see about 6% CPU utilization even when the editor is completely idle.  When ide-haskell is disabled Atom goes back to the 0-1% range.

I ran the development tools profiler and found Atom sleeps for about 16ms, runs for 1ms, then repeats.  I disabled ide-haskell and took another profiler sample and found a more reasonable pattern of 400ms sleep between short bursts of activity.

While this is a pretty minor issue it would still be nice to avoid wasting CPU and battery unnecessarily.  I might try to fix this myself but would appreciate some pointers on which part of the code might be causing the issue.

I think this is unrelated to #109. I'm only seeing moderate amounts of CPU use, nothing like the 150% mentioned there.

**Comment by lierdakil** [comment]
Sigh. I have no idea. If you do nothing, ide-haskell and friends shouldn't do anything really. As a wild guess, it might be child_process polling pipes, but I'm not exactly sure. You can try disabling ghc-modi in haskell-ghc-mod settings to test this idea.

**Comment by spencerjanssen** [comment]
Disabling ghc-modi didn't seem to change anything.  A few more observations:

 * The problem goes away when the panel is hidden
 * In the timeline view of the debugger, the frequent wakeups contain three events in this order: Recalculate Style, Update Layer Tree, Composite Layers
 * The Recalculate Style event says "Elements affected: 1"
 * None of these events seem to coincide with a timer firing, and none of them have JS stack traces attached.

**Comment by spencerjanssen** [comment]
Did some poking around in the Elements inspector and found an `ide-haskell-progress-bar` element with `visibility: hidden` in the panel.  On a hunch I deleted it and found that the excessive wakeups were gone.  I noticed the CSS attached to that element has some animation properties, perhaps that's the issue?

**Comment by lierdakil** [comment]
I suppose this can be closed
