### ISSUE TITLE
Is it possible for ide-haskell to work with nuclide-remote-projects?

### ISSUE THREAD

**Issue by kaizhang** [atom-haskell/ide-haskell#124]
I edit my codes on a remote server through nuclide-remote-projects(https://atom.io/packages/nuclide-remote-projects). It would be nice if ide-haskell is compatible with nuclide-remote-projects and supports remote checking.

**Comment by lierdakil** [comment]
Literally no idea how I would even approach this, and not much time on my hands. If anyone wants to give this a try, feel free to take it up.
