### ISSUE TITLE
ghc-mod throws error on every check inside a cabal or stack project

### ISSUE THREAD

**Issue by liefswanson** [atom-haskell/ide-haskell#125]
appears to fail with every attempt to run a check while inside a cabal or stack project, but does not fail if I am just editing a lone haskell file. 

the error i get is.... 
```
Haskell-ghc-mode: ghc-mode check
/path/to/current/file.hs failed with error code 1

ghc-mod: Language/Haskell/GhcMod/Types.hs:404:10-39: No instance nor default method for class operation put.
```

This appears to be a problem with ghc-mod, but i am not really sure.

I am running 
atom 1.1.0 and 1.2.0beta
arch linux kernel 4.2.5-1
ghc 7.10
stack 0.1.6.0
cabal 1.22.4 (library) 1.22.6 (exec)
ghc-mod 5.4.0.0
stylish-haskell 0.5.14.3
hlint 1.9.22

**Comment by lierdakil** [comment]
Upstream issue https://github.com/kazu-yamamoto/ghc-mod/issues/678

**Comment by lierdakil** [comment]
See also https://github.com/kazu-yamamoto/ghc-mod/issues/680#issuecomment-154161380

**Comment by liefswanson** [comment]
thanks for the links! that was very helpful.
