### ISSUE TITLE
Annoying tooltip messages and tooltip issue with scrolling

### ISSUE THREAD

**Issue by jbracker** [atom-haskell/ide-haskell#126]
Hello,

I am experiencing the same hlint issue as #95 . The parse error is not really upsetting me, but the fact that a tooltip of the parse error keeps popping up in the middle of my editor screen, independent of where my cursor or mouse is. This is especially painful, when I am editing the section beneath the tooltip, since editing does not close it!

My suggestion would be to make tooltip aware of the cursor/mouse position and make them avoid that position so they do not block the view. Aside that they should definitely close as soon as your cursor is beneath them or the mouse tries to position the cursor beneath them. They should also only open when the cursor is actually above the source position of the error.

Something unrelated I also noticed: Tooltips don't automatically close when you scroll them out of view. Which leads to the odd effect that they overlap with other parts of atom. There is no usability issue here, as they close as soon as you click somewhere, but it would be nice if they close automatically

Sorry if this is not the right place to report this error.

Installed packages:
autocomplete-haskell 0.6.2
haskell-ghc-mod 1.1.2
ide-haskell 1.3.1
ide-haskell-cabal 1.0.0
language-haskell 1.5.0
minimap 4.16.0
minimap-selection 4.3.1

**Comment by lierdakil** [comment]
1.3.3 should hide tooltips more robustly. Also see this ide-haskell option:
![image](https://cloud.githubusercontent.com/assets/7275622/11117862/510108aa-894e-11e5-87fe-b03f35f6e2e1.png)

**Comment by jbracker** [comment]
Indeed, it does. Thank you!
