### ISSUE TITLE
Command to add type inference for a top-level function above it?

### ISSUE THREAD

**Issue by mrapogee** [atom-haskell/ide-haskell#130]
Could save a lot of time typing out the types if they can be inferred. Obviously can't infer every time, but could save a lot of redundant typing.

**Comment by lierdakil** [comment]
There's a context menu option for that
![image](https://cloud.githubusercontent.com/assets/7275622/11252564/e209eb34-8e47-11e5-9b49-c80f9a90f049.png)

Also, available via command palette.
![image](https://cloud.githubusercontent.com/assets/7275622/11252598/1a4fa344-8e48-11e5-8c52-b14f0b791f68.png)

See [here](https://github.com/atom-haskell/haskell-ghc-mod#keybindings) for other commands you might find useful and instructions on how to bind those to keys.

These commands are ghc-mod specific (or backend-specific, generally speaking, but only support for ghc-mod was implemented) hence those were moved out of core package.

**Comment by mrapogee** [comment]
Awesome! I apologize for my ignorance.
