### ISSUE TITLE
go to decl not working

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#131]
I tested the goto declaration on 
 - qualifed names
 - regular names

defined :
 - in the current file
 - in the current package
 - in an other package

via:
 - cmd+shift+p+"gotodecl"
 - right click

but none of them seems to be working
(I have all packages up to date and atom up to date)

**Comment by lierdakil** [comment]
Out of scope. These commands are part of [symbols-view package](https://atom.io/packages/symbols-view). You need `.tags` file for it to work. See [hasktags](https://github.com/MarcWeber/hasktags) or something like that.

**Comment by rvion** [comment]
oh, cool, didn't know
