### ISSUE TITLE
Truncated type information for a special type operator

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell#136]
This should be an easy fix, but it might be a ghc-mod issue. Not sure. Anyways. I define a type synonym using a type operator like this

    type (s :: Symbol) ::: a = a

This lets me annotate parameters in type signatures. Now let's say I define a function like this

    testFunction :: "param1" ::: Int -> "param 2" ::: String -> Int
    testFunction a b = 5

What I'd like to get from this is the parameter names in the type info window when I start writing "testFunction". But what I get is this

![ugpeqek](https://cloud.githubusercontent.com/assets/370627/12820761/c967d658-cb60-11e5-8144-d82d3accdc09.png)

It gets cut off at the `:::` part. If I instead use `:-:` as the operator it shows the whole signature.

It's a minor thing but I'd really like to have it work with `:::`.

**Comment by lierdakil** [comment]
haskell-ghc-mod-1.6.5 should fix this. Let me know if it doesn't

**Comment by LukaHorvat** [comment]
Can confirm it works!
