### ISSUE TITLE
How to use "Jump to definition"?

### ISSUE THREAD

**Issue by PetrGlad** [atom-haskell/ide-haskell#137]
I am sorry if this is described elsewhere, but I could not find a way to use "jump to definition" (which is marked as "done" in the todo list).
Symbols view is empty in Haskell file, ctrl+b helps to select all occurrences in current file but this won't help if symbol is declared in other file. ghc-mod backend seem to work fine and declaration location is shown in tool-tip autocomlpetion also works.

How do I use "jump to definition"? Is there a way to configure it?

I use Atom 1.4.1, haskell-ghc-mod 1.6.6, ide-haskell 1.3.6, ghc-mod 5.5.0.0

**Comment by lierdakil** [comment]
There are two options. One is using [ide-haskell-hasktags](https://github.com/atom-haskell/ide-haskell-hasktags). Another is relying on ghc-mod with `haskell-ghc-mod:go-to-declaration` command. You can bind it to any hotkey you want. It's also accessible from command palette, or from context menu (ghc-mod → go to declaration)

**Comment by PetrGlad** [comment]
Thanks.
