### ISSUE TITLE
Extra newlines in errors/warnings

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell#143]
So I've updated to the latest release which adds coloring to warnings and it's great. But my warnings seem to have an extra new line between every line of text:
![](http://i.imgur.com/Wfyw0JE.png)

Is this a bug with my setup?

**Comment by lierdakil** [comment]
Doesn't happen for me:

![image](https://cloud.githubusercontent.com/assets/7275622/13350955/749a0a3e-dc94-11e5-9dda-342b56189cc4.png)

Do you have a custom stylesheet applied?

**Comment by LukaHorvat** [comment]
Ok, I'll investigate.

**Comment by lierdakil** [comment]
For reference, every line is wrapped in `<span class="hint message haskell">` (due to how tokenizer works), so that might provide some insight.

**Comment by lierdakil** [comment]
If I had to guess, probably `line-height` is set somewhere? At least that's not `margin` or `padding`, since that doesn't work on inline elements.

**Comment by LukaHorvat** [comment]
Yeah, it seems the `line-height` is set to a large amount. Probably one of the themes. I'll just add a custom style for now.

**Comment by lierdakil** [comment]
Something along the lines of

```less
ide-haskell-item-description span {
    line-height: normal;
}
```

should work. I'll include it it ide-haskell stylesheet if this comes up for anyone else.

I'm also curious what package causes this. Might be worth noting in readme.

Also, I prefer to leave it open for now in case someone else runs into this issue.
