### ISSUE TITLE
Ability to freeze which project to compile.

### ISSUE THREAD

**Issue by wdanilo** [atom-haskell/ide-haskell#148]
Hello! 
I'm developing a bunch of libraries and I normally want one of the libraries to be compiled whatever source I change. I would love to be able to explicitly mark which project is my main project that I want to compile, not based on the currently open source file. Would it be possible to add such feature? Thank you very much! :)

**Comment by lierdakil** [comment]
Done in ide-haskell-cabal v1.2.0. Ide-haskell-stack will be killed shortly after I merge it into ide-haskell-cabal, so I don't think I will implement it there. Sorry if you're using stack.

**Comment by wdanilo** [comment]
Of course I'm using stack. Do you mean it will not work well with stack in the future? I dont know anyone right now that is using just cabal to develop packages, but know few companies that fully depend on stack and breaking support for it would be the worst thing we can do when thinking about haskell support in any IDE.

**Comment by lierdakil** [comment]
Don't panic. I never said anything about not supporting stack. You'll
just have to wait while I merge stack support back into
ide-haskell-cabal. This might take a while though.

2016-04-03 22:42 GMT+03:00, Wojciech Daniło <notifications@github.com>:

**Comment by wdanilo** [comment]
Ok, that's good :) I was just trying to ensure it will work next to each other :) I have misread your response - if you plan to kill `ide-haskell-stack` after merging it to the second backend it's completely ok :) Do you know any approximate timeline this will be available for stack too? By the way (in order not to open second small ticket) - will there be also possibility to define an action after build - like running the executable? Thank you :)

**Comment by lierdakil** [comment]
As for your first question, probably somewhere around a month or so --
I have to sort out a horrible mess that is initial configuration of
ide-haskell first, and I don't have much time to dedicate to that at
the moment. Sorry.

As for second, there are no plans for this at the moment. I'm not
entirely sure what the use-case would be for that. Could you
elaborate?

2016-04-03 22:52 GMT+03:00, Wojciech Daniło <notifications@github.com>:

**Comment by wdanilo** [comment]
Of course :) I would be really thankful though if you'll bring this functionality as fast as possible, because it doesnt seem very big (regarding its done in the cabal backend) and its so important for all the stack-users. I completely understand your time limits and I'm very thankful for bringing haskell-ide to live, it is really a great job! :)

The second one is very simple - I've got a program that produces a binary called "mybin". I want simply to run this binary after the compilation to see the results in the terminal. This is something different than running tests. Stack gives you such ability simply by invoking `stack exec mybin`. In fact If you'll allow to run post- / pre- compilation scripts that would be wonderful! :)

**Comment by rvion** [comment]
@wdanilo if you're using stack, why don't you just run `stack build --fast --file-watch --exec="/x/y/z/mybin"`in a terminal ?

**Comment by wdanilo** [comment]
@rvion: because I want atom to display errors and indicate in which line they've occurred, so I want my workflow to base on `ide-haskell`. Is there any other way to do it in atom?

**Comment by rvion** [comment]
@wdanilo those are two separate things:

On one side you have the ide-haskell atom plugin, that uses ghc-mod under the hood to provide ide-related features. ghc-mod will probably typecheck your code, but very unlikely generate an executable file.

On the other side, stack is a build tool, and it has all necessary options to generate an executable where you want and run it.

Wen you say
> In fact If you'll allow to run post- / pre- compilation scripts that would be wonderful! :)
you imply that ide-haskell plugin compile your code, which (I think) is not the case. 

When you say:
>  I want simply to run this binary after the compilation to see the results in the terminal.
What terminal are you speaking about ? Do you expect atom to spawn a terminal ?

**Comment by rvion** [comment]
also, you probably don't want to start your binary running the command `stack exec mybin` because `stack exec` is slow. It parse stuff, check things, and cook some custom env before running your actual command. if your executable does not care about stack related stuff, just launch if directly (stack install will put the bin in `~/.local/bin`, and stack build will put it in some `./.stack-work/dist/...` subfolder

**Comment by wdanilo** [comment]
@rvion: ghc-mod is useless for me at the moment cause it doesnt understand the code, because we use some template-haskell magic here and I have to rely on errors thrown by stack while it compils the packages.

`ide-haskell` (or more specific its stack backend) gives you an option: `Haskell IDE -> stack -> build project` which invokes stack. In the options of this plugins you can provide stack command line args, but you cannot provide any pre / post scripts at the moment. @lierdakil mentioned he will merge this backend into `ide-haskell` or its cabal backend, so I mentioned about it here.

I'm sorry for using word "terminal" - I meant that I want to see the results in the `ide-haskell` output window.

**Comment by rvion** [comment]
@wdanilo well, I guess there should be an issue open in ghc-mod so, because it should be able to understand the code. 

also, from what I understand, ide-haskell don't have a real stack backend, stack is only used to get dependencies,options, etc. (probably done via ghc-mod as of now).

from what I understand, even if ide-haskell atom plugin provides a `stack build` command, it doesn't mean that it uses stack to get type errors. it is (again, from what I understand) unrelated. So, even if the error pane is empty, you would still have to trigger a full `stack build`, then to run your `mybin` exe, and it might be really long to finish. IMO, it seems weird to have an option to trigger a full stack build everytime the local file typechecks according to ghc-mod.

**Comment by wdanilo** [comment]
The authors of ghc-mod write in its documentation it does not and will not (for now) understand the TH generated code / code using CPP pragmas and we should not suspect it will be available shortly. In fact it was never possible.

I think you are wrong in your second and third point. I'm using thi option (the ide-haskell stack backend and "build" command to evaluate stack under the hood and in fact ide-haskell is able to parse the errors and display them in the atom editor (and in the error pane). Please note that I'm not using ghc-mod here.

Additional I don't want to trigger full stack build everytime a file changes. I want to trigger it by hand - like now, but be able to "pipe" it to execution of produced binary. Does it make sense to you?

**Comment by wdanilo** [comment]
Additional - I dont think that basing on ghc-mod errors only is good in general. ghc-mod is just separate prohect from ghc, it doesnt support all of its functionalities, it is sometimes slow (in comparison to just building the project) and could potentially give different results. `ide-haskell` is able currently to display the errors directly from `stack` and thats cool, because it is displaying errors that compiler has thrown - like in any other decent IDE. The things that are missing here are just the ability to run post / pre build commands and freeze the target project (like described in the first post).

**Comment by rvion** [comment]
yep, everything is clear now, I didn't understand 
 - the way you want to use the ide plugin
 - that you were not able to use ghc-mod because of some CPP pragmas stuff.
 - that you were using https://github.com/atom-haskell/ide-haskell-stack (I didn't even know about its existance, because I'm using stack based project with ide-haskell-cabal)

Personally, I'm happy with ghc-mod for errors in atom + have some terminal open with `stack build --file-watch --exec=...` so it does what you want (except not it an atom pane). 

As a workaround until this is implemented, you could just install some other atom package providing terminal emulation features, and you would just have to open a pane in atom, and launch a command that watch for your binary to re-run it automatically. After each manually triggered stack build, the pane in atom running your command would show the output. 

-----------------

> Additional - I dont think that basing on ghc-mod errors only is good in general. ghc-mod is just separate prohect from ghc, it doesnt support all of its functionalities, it is sometimes slow (in comparison to just building the project) and could potentially give different results. 

I mostly disagree. From my experience, ghc-mod does a good job on most cases, and is faster that recompiling via stack

> ide-haskell is able currently to display the errors directly from stack and thats cool, because it is displaying errors that compiler has thrown - like in any other decent IDE. The things that are missing here are just the ability to run post / pre build commands and freeze the target project (like described in the first post).

Again, I mostly disagree. For example, I couldn't live without being able to quickly select some expression and see
 - what type it is.
 - what is the smallest enclosing haskell expression containing my sub-selection

any other decent IDE just running the compiler and parsing it's output is not able to do such things.

![image](https://cloud.githubusercontent.com/assets/2150990/14235230/10501a88-f9f8-11e5-922b-58b109110454.png)

but that's very personal :)

**Comment by wdanilo** [comment]
`As a workaround until this is implemented, you could just install some other atom package providing terminal emulation features, and you would just have to open a pane in atom, and launch a command that watch for your binary to re-run it automatically. After each manually triggered stack build, the pane in atom running your command would show the output.` - thats not true. I dont want to do it, because then ide-haskell will not show the errors from stack directly in the code editor / in the error pane (now it is doing like that, so I'm happy staying with my current workflow).

Regarding the second topic - of course, ability to see the type after mouse hover is great. I'm not thinking it should not exist. I think it should exist side-by-side with displaying errors directly from stack.

To clarify one more thing - as I've written before, ghc-mod doesnt work with BOTH TH and CPP, not only CPP :)

**Comment by rvion** [comment]
> As a workaround until this is implemented, you could just install some other atom package providing terminal emulation features, and you would just have to open a pane in atom, and launch a command that watch for your binary to re-run it automatically. After each manually triggered stack build, the pane in atom running your command would show the output.

>>  thats not true. I dont want to do it, because then ide-haskell will not show the errors from stack directly in the code editor / in the error pane (now it is doing like that, so I'm happy staying with my current workflow).

It would work. you would still trigger the build via ide-atom-stack. Your workflow wouldn't change. I'm only speaking about adding one other component that check when the executable has been rebuild to re-run run it + show it to you in atom. This new component would just complement your workflow by checking every x00 ms if the modified date of your executabe changed to re-run your cmd.

> To clarify one more thing - as I've written before, ghc-mod doesnt work with BOTH TH and CPP, not only CPP :)

 - Well, for my use of TH, it does work. Maybe you're speaking about something else.
    ![image](https://cloud.githubusercontent.com/assets/2150990/14235360/483544ce-f9fc-11e5-8777-b6d55046dbb7.png)

 - Also, it seems that CPP is also supported to some extend by ghc-mod (I don't say there is no issues, but your claims are wrong)
    (see https://github.com/DanielG/ghc-mod/search?utf8=%E2%9C%93&q=cpp)
    ![image](https://cloud.githubusercontent.com/assets/2150990/14235406/adc449d8-f9fd-11e5-8923-cf7ffb1433cb.png)

    ![image](https://cloud.githubusercontent.com/assets/2150990/14235402/a0d31236-f9fd-11e5-8377-156dd9dafafe.png)

**Comment by wdanilo** [comment]
That's correct - it works with simple things, but if you for example try to create a name (like top-level variable name) with TH, it will not see it. There are other problems too. The same goes with CPP pragmas - some recursive evaluations are just not supported. It also does not support ghc > 8.* and is much slower than re-running stack for really big projects (see update in my previous post).
 
Anyway, I think this is just an off-topic from the general discussion about `ide-haskell`. I just want to be able to run post-compilation scripts when using the stack backend :) 

Regarding your solution - you're right - running such external utility to just re-run executable when it changed would work and is for now a good solution indeed. Still I would love to see it in the same output pane all other output from stack-ide goes :)

**Comment by rvion** [comment]
@wdanilo

I tested atom-ide-stack, and what you want is already in here...
My first answer had the info to make it work...

![image](https://cloud.githubusercontent.com/assets/2150990/14235535/87a4843a-fa01-11e5-8e9c-42eece7eb063.png)

![image](https://cloud.githubusercontent.com/assets/2150990/14235520/073569a4-fa01-11e5-871a-78b94035be0d.png)

> I'm developing a bunch of libraries and I normally want one of the libraries to be compiled whatever source I change. I would love to be able to explicitly mark which project is my main project that I want to compile, not based on the currently open source file. 

if you read the stack documentation, you'll discover more stuff like how to compile a specific target, regardless of your current open file in the editor.

Happy hacking with your ghc 9 and invisible TH functions code that ghc-mod totally not see. :)

**Comment by rvion** [comment]
@lierdakil if I understand correctly the 2 problems raised in this thread, this issue can be closed.

**Comment by wdanilo** [comment]
@rvion: Oh, I didn't kno I can pass the `--exec` to the build command. Give me few minutes to check it out, if it works like you describe that really solves this issue. Thank you for pointing it out! :)

Regarding the compilation of a specific target regardless of my current open file, are you talking about passing `--stack-yaml` arg or about something else? Unfortunetally passing custom `stack-yaml` config does not work, because stack expands all relative paths from the config from the current working directory, that is set by haskell-ide. If there is other solution that I don't know about, I'll happy hear about it! :)

**Comment by wdanilo** [comment]
@rvion Ok, you are right - the `--exec` parameter does the job. Thank you, you've saved my life from ugly work-arounds! :) What about the second issue? Do you have any other solution for it?

**Comment by wdanilo** [comment]
@rvion: I've checked it and indeed - the `--exec` option does the job! Thank you for saving my life from ugly work-arounds! :) Do you have any idea if are we able to proceed with the second issue now? I've got an easy workaround for it now - I've just created `stack` alias that goes into the desired folder before running real stack, but its a bit ugly for long-term usage. 

Regarding the CPP support we were talking before - is it possible to pass some flags to ghc-mod while using it in `ide-haskell` at the moment? It fails in one place here because it doesn't know about a lag that is passed to it (via stack-yaml config).

**Comment by lierdakil** [comment]
So, I have merged stack support into ide-haskell-cabal a while back, so choosing project/component to build should be rather straightforward now. Closing this issue.
