### ISSUE TITLE
Ability to change the font size

### ISSUE THREAD

**Issue by wdanilo** [atom-haskell/ide-haskell#149]
Hello! I would love to ask for one more thing in `ide-haskell` - the ability to change the font size. I'm using atom on a very high-dpi monitor and the default font is hardly readable here. Would it be possible to just add a field in configuration where I can write my preferred size? :)

**Comment by rvion** [comment]
Font size is unrelated to ide-haskell.
Configuring the font-size is done at the atom editor level.

![image](https://cloud.githubusercontent.com/assets/2150990/14405881/4a2bb28a-fe99-11e5-9d4f-ab1ed8d875f3.png)

**Comment by wdanilo** [comment]
I'm talking about the font-size in the panel provided by `ide-haskell`. It is not affected by the editor font size: 
![screen shot 2016-04-09 at 21 37 01](https://cloud.githubusercontent.com/assets/1623053/14405952/519e11be-fe9b-11e5-9232-f6a0146e3143.png)

**Comment by lierdakil** [comment]
See https://github.com/atom-haskell/haskell-ghc-mod/issues/122

**Comment by wdanilo** [comment]
Great! Thank you very much for this hint! :) Still, I think it should be available in the settings for wider-audience easy access :)

**Comment by lierdakil** [comment]
Let's just say that doing this in settings is harder than it needs to be, and *will* clash with Atom's stylesheet. So I figure that using standard Atom approach with custom stylesheet is the way to go. What I should do is describe this in readme. Don't worry, that's on my todo list.

**Comment by wdanilo** [comment]
Sounds great! Thank you for the help! :)
