### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by AshtonFriel** [atom-haskell/ide-haskell#154]
In styles/ide-haskell.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements. ide-haskell not working or showing up when opening Haskell source file.

**Comment by AshtonFriel** [comment]
lol just posted this to get the message out no need to name call

**Comment by lierdakil** [comment]
Haha. Yeah, now that I look at it, it sounds kinda mean. No offence meant though, as you probably figured.
