### ISSUE TITLE
Disable cabal build on save?

### ISSUE THREAD

**Issue by MarkZander** [atom-haskell/ide-haskell#155]
When doing a save a lot of errors are printed such as not being able to find imports.

When selecting Haskel IDE->Stack->Build project everything builds just. While not fatal this is a major distraction.

How can things be set up to avoid cabal build on save? Can stack build on save be set up?

Thanks in advance.

**Comment by lierdakil** [comment]
Untick 'on save check' in haskell-ghc-mod options.

**Comment by MarkZander** [comment]
Thanks!

Mark
