### ISSUE TITLE
Do not replace file contents if sub-command returned error

### ISSUE THREAD

**Issue by cblp** [atom-haskell/ide-haskell#158]
I have some complicated Haskell code, and stylish-haskell refuses to stylish it:
```
stylish-haskell: Language.Haskell.Stylish.Editor.applyChanges: refusing to make overlapping changes
```
I don't know what this means but editor removes the whole file contents.

stylish-haskell process returns 1. In this case the file contents must not be replaced.

**Comment by lierdakil** [comment]
Should be fixed in 1.6.3.
