### ISSUE TITLE
Error with Unicode prompt on Cabal REPL under Windows 10

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell#159]
1. Create file ".ghci" in your project's root
2. Add inside 

> :set prompt  "\x03BB> "
1. Open this project with Atom
2. Haskell IDE | Open REPL 
   and it will give error:

> <stdout>: hPutChar: invalid argument (invalid character)

**Comment by lierdakil** [comment]
First of, prompt settings will be overwritten by ide-haskell-repl, since it needs to set a very particular prompt to parse ghci's output.
Second, this seems to be Windows-specific issue,  due to the fact that Windows terminal uses single-byte encoding. I'm not sure I can do much about that. Anyway, I tried to hard-set encoding to utf8 in 0.0.21. See if it works.

**Comment by varosi** [comment]
This file is present there, because of project already has it for work
directly from the console. And if I write:

> stack ghci

in console - everything is working and I see lamda as a prompt. As I open
console properties, my code page is "866 (OEM - Russian)".

2016-05-12 20:35 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
So... does ide-haskell-repl@0.0.21 work or does it crash all the same?

**Comment by lierdakil** [comment]
Nevermind, sorry, misread your comment.

**Comment by lierdakil** [comment]
This seems to be [known GHC bug](https://ghc.haskell.org/trac/ghc/ticket/8118) -- not sure what I can do here.

**Comment by varosi** [comment]
It is strange, because from command-line (console) I don't have problems to
run GHCi and show lambda Unicode character.

2016-05-15 1:29 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
It entirely depends on what terminal emulator you use.

**Comment by varosi** [comment]
I use the original one embedded into Windows 10 - cmd.exe.
If you wish I could check it on Windows 7 around here?

Are there problems somewhere with encoding/decoding on the data flow from
GHCi to Atom?

2016-05-17 12:14 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
I doubt that Win7 will be any different.

There is a problem all right. This problem is "GHCi on Windows seems to ignore the fact that pipe is utf-8 encoded, and guesses encoding incorrectly".

**Comment by lierdakil** [comment]
I guess we could try forcing encoding in some way, but I have no idea how to go about it, save from patching GHCi.

**Comment by lierdakil** [comment]
Also, a quick sanity check, do your ide-haskell-repl settings look like this?

![image](https://cloud.githubusercontent.com/assets/7275622/15330451/8f3c9b84-1c65-11e6-8702-4f38b9f76503.png)

(note: there could be `ghci` in 'Command Arguments', doesn't matter with newer stack versions)

**Comment by varosi** [comment]
Yes, with "stack" there it is working fine on Stack projects.

2016-05-17 19:29 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by varosi** [comment]
May be it will be good if project is Stack based to use "stack" for REPL.

2016-05-17 22:03 GMT+03:00 Vassil Ognyanov Keremidchiev <varosi@gmail.com>:

**Comment by lierdakil** [comment]
Okay, here's one idea that probably won't work. Try running `process.env.LC_ALL="en_US.UTF-8"` in developer console before launching repl. I'm pretty sure this is ignored on Win, but maybe I'm wrong...

**Comment by varosi** [comment]
Here is the actual console output after the test:
process.env.LC_ALL="en_US.UTF-8"
"en_US.UTF-8"
ide-haskell-repl: <stdout>: hPutChar: invalid argument (invalid character)
ghci.coffee:71
ide-haskell-repl: ghci.coffee:71
ide-haskell-repl: ghc.exe: warning: _tzset from msvcrt is linked instead of
__imp__tzset


2016-05-17 23:31 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
Okay, I could *not* reproduce this on Windows 7.

**Comment by varosi** [comment]
Problem still persist on Windows 10. My System locale is "Bulgarian
(Bulgaria)". I think that this could be related to the problem somehow.
It's not default US/EN.

2016-05-18 20:17 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
The system that I tested on had cp1251 as default encoding with Russian locale. Console is probably cp866-encoded (didn't check). That's pretty similar to what you have. I didn't get the chance to test on Win10 yet though. So, just to set the record straight while I look for spare Win10 system, are you positive that `:set prompt "\x03BB> "` is the issue, and not something else?

P.S. I see you changed title to specify `cabal repl`. Does `stack repl` also manifest this problem, or is it `cabal repl`-specific?

**Comment by varosi** [comment]
It is only cabal-specific. On stack repl there is no problem.

2016-05-22 16:57 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by varosi** [comment]
Yes, the problem is with: :set prompt "\x03BB> "

2016-05-26 15:58 GMT+03:00 Vassil Ognyanov Keremidchiev <varosi@gmail.com>:

**Comment by lierdakil** [comment]
Okay, so I finally got around to testing this, and I wasn't able to reproduce it on Win10 with Atom 1.15 and ide-haskell-repl-0.6.0. Is this still an issue?

**Comment by varosi** [comment]
Yes, currently there is no problem on those latest versions. Thanks a lot!
