### ISSUE TITLE
Ide-haskell could not spawn stylish-haskell

### ISSUE THREAD

**Issue by jjohnson382** [atom-haskell/ide-haskell#161]
Ide-haskell could not spawn stylish-haskell
Error: spawn stylish-haskell ENOENT

<img width="445" alt="screen shot 2016-05-24 at 10 16 25" src="https://cloud.githubusercontent.com/assets/19390545/15507347/3e2c9b48-2199-11e6-8122-e80ea1786a24.png">

**Comment by lierdakil** [comment]
Do you have stylish-haskell installed? Is it on your PATH? Because it really seems like it isn't.
