### ISSUE TITLE
Shortcut to dismiss errors and warnings

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell#162]
Currently I often encounter an annoying situation where there's an error in my code and when I start correcting it, the error location goes along with the cursor as I type. This results in the error message popup showing as soon as I press any key and it blocks the view so I can't see what I'm actually typing.

Could you please add a shortcut that I can press to dismiss all error in the file until I save the document again?

**Comment by lierdakil** [comment]
Terribly sorry about missing this report, I was preoccupied back when this was filed and then I forgot.

Should be fixed in 1.6.7.
