### ISSUE TITLE
Stack Docs Misleading

### ISSUE THREAD

**Issue by AshtonKem** [atom-haskell/ide-haskell#163]
The main docs for ide-haskell state that Stack is not supported, which apparently is not true. Furthermore ide-haskell-cabal apparently supports cabal and stack, with ide-haskell-stack being deprecated. This is non-obvious for users trying to setup ide-haskell.

**Comment by lierdakil** [comment]
Yes, sad truth is I can often forget to update docs. Thanks for bringing this to my attention. Updated in repo, next release will have it updated on atom.io.
