### ISSUE TITLE
A GUI button for closing/toggling the panel

### ISSUE THREAD

**Issue by radix** [atom-haskell/ide-haskell#165]
It'd be nice if I didn't have to remember the name of the command to toggle the ide-haskell build panel all the time -- a small "x" or down-arrow-style button would be nice to have in the toolbar in the ide-haskell panel.

**Comment by lierdakil** [comment]
It's near the top of ide-haskell menu... Besides, if you find yourself
toggling panel often, you might consider binding a key to this command.
8 июня 2016 г. 11:45 PM пользователь "Christopher Armstrong" <
notifications@github.com> написал:

**Comment by radix** [comment]
If you disagree with my suggestion, then that's okay; but a menu item is not the same as a GUI button in the panel. My desktop environment on Ubuntu doesn't even display menus by default unless I hover my mouse at the top of the screen, so I didn't even know about the IDE-Haskell menu.

I think a GUI button would be:

- more discoverable
- better for casual usability
- consistent with other atom packages that provide their own panels

**Comment by lierdakil** [comment]
That's a reasonable argument, but by the same logic that would require a button in status bar or something to *show* ide-haskell panel. And let's face it, statusbar is severely overcrowded as it is.

**Comment by lierdakil** [comment]
Since panel now allows minimizing output part, for something like this:
![image](https://cloud.githubusercontent.com/assets/7275622/21967242/41a59134-db94-11e6-8a58-aa9f3a17b684.png)
I don't think this is relevant anymore. Closing.
