### ISSUE TITLE
Document Stack support

### ISSUE THREAD

**Issue by spinda** [atom-haskell/ide-haskell#166]
re: #82

Apparently you support Stack now. Why not tell the world? :wink:

I'd submit a PR but I don't know what setup is involved.

**Comment by lierdakil** [comment]
Duplicate of #163.
9 июня 2016 г. 6:34 AM пользователь "Michael Smith" <
notifications@github.com> написал:

**Comment by radix** [comment]
I suppose this ticket should be closed, if it's a duplicate?

**Comment by lierdakil** [comment]
Yes. I didn't have access to github at the time, and later just forgot.
