### ISSUE TITLE
Popups doesn't disappear in beta atom release

### ISSUE THREAD

**Issue by mpkh** [atom-haskell/ide-haskell#167]
mirrored issue: https://github.com/atom/atom/issues/11946

strange but happens only with haskell for me

**Comment by majorgilles** [comment]
Also happens for me on arch linux with the following versions:

Atom    : 1.9.0-dev-3f85c1d
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Everything is configured and working fine, but the type popups don't autohide

**Comment by lierdakil** [comment]
I'm sorry about this, I haven't been following atom development lately, so I missed this change when it happened back in May. Thank you for bringing this to my attention.

**Comment by lierdakil** [comment]
Okay, this should be fixed by 1.6.6, although this should've been working fine with a deprecation warning, but upstream accidentally messed that up (which should be fixed by Monday). Let me know if you still experience problems.

**Comment by majorgilles** [comment]
Fixed on my end
