### ISSUE TITLE
Failed to run undefined \n spawn EACCES

### ISSUE THREAD

**Issue by TorosFanny** [atom-haskell/ide-haskell#168]
All the ide-haskell's functions work fine, except Prettify. And when I edit a .hs, save a .hs or open a .hs file, the editor prompts a message:

> Failed to run undefined
> spawn EACCES

PS: My stylish-haskell is in /home/qs/.cabal/bin/stylish-haskell. I have set it well.

**Comment by lierdakil** [comment]
Triple-check that 'ide-haskell.stylishHaskellPath' is set in config. If it
is, try un-installing and re-installing ide-haskell package, maybe Atom's
compilation cache got corrupted.

2016-06-16 12:38 GMT+03:00 TorosFanny <notifications@github.com>:

**Comment by TorosFanny** [comment]
I try to install ide-haskell again, but failed with this:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.12/node-v0.36.12.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Linux 4.6.2-1-ARCH
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.12" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/qs/Config/atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by lierdakil** [comment]
Sorry about long silence. Last error is an internet connection failure apparently =\ that said, it seems to me your Atom installation is corrupted somewhat.

**Comment by TorosFanny** [comment]
My OS is ArchLinux and npm's version is 3.10.6-1 and nodejs's version is 6.4.0-1. Is that too new for atom-editor? I recall that it seems to be the reason.  Because when I tried to install atom-editor in ArchLinux, it reports:

> (node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by lierdakil** [comment]
You could try installing Atom from arch-atom (unofficial) repo: https://github.com/tensor5/arch-atom. I can at least confirm that it works fine for me.

**Comment by TorosFanny** [comment]
yes,  thank you for still remembering this. The new version of atom and npm don't have this bug
