### ISSUE TITLE
user error (ghc not found) when running ghc-mod

### ISSUE THREAD

**Issue by ijuma** [atom-haskell/ide-haskell#17]
Interesting plugin. :)

Not sure if this is a bug, but I didn't find a mailing list for questions, so I thought I'd try here. I am getting the following issue:

```
got something strange from ghc-mod check: ["user error (ghc not found)", unique: function]0: "user error (ghc not found)"length: 1__proto__: Array[0]

got something strange from ghc-mod lint: ["user error (ghc not found)", unique: function]0: "user error (ghc not found)"length: 1__proto__: Array[0]
```

If I run the check command manually using the path I configured in the settings, no errors are returned:

```
➜  lm-notes-html-gen git:(master) ✗ /Users/ijuma/.cabal/bin/ghc-mod check Main.hs
➜  lm-notes-html-gen git:(master) ✗
```

`Prettify` works fine by the way. I am using Mac OS X Mavericks and GHC 7.8.3.

Any ideas?

**Comment by jeffreyrosenbluth** [comment]
@ijuma 
How did you fix this, I have the same problem but I don't know how to get ghc in my path from Atom's context?
