### ISSUE TITLE
Tooltip bug with type-level strings:  ":: Fn (Tag \" instead of  ":: Fn (Tag  "stuff" a) ()"

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#170]
🍏  gitter mark shows correct type
![image](https://cloud.githubusercontent.com/assets/2150990/17890245/08c45368-6935-11e6-8d8d-28f3862413b8.png)

🔶 hovering info 1st line is bad, but snd is correct
![image](https://cloud.githubusercontent.com/assets/2150990/17890256/29cd894e-6935-11e6-901d-0974fb79228d.png)

🔴  when selecting code, info is wrong (this is what I use most)
![image](https://cloud.githubusercontent.com/assets/2150990/17890262/2fa0deca-6935-11e6-8d7f-c6ac2d4b5718.png)

**Comment by rvion** [comment]
extensions in file are
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}

**Comment by lierdakil** [comment]
I'll have to ask for a testcase, if possible. Or at least github link to relevant project.

**Comment by lierdakil** [comment]
Nevermind, I think I've got it. Check if v1.17.2 works.
