### ISSUE TITLE
Show type of the symbol under caret on the "Completion Hint Panel"

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell#172]
I think the panel would be much more useful if it shows type or info for the current symbol, i.e. the symbol (type, function, value, etc.) on which the cursor currently is.

**Comment by lierdakil** [comment]
Maybe. But there are a lot of associated performance concerns. Besides, that's not the point. The point is to show what are the types of arguments of recently autocompleted function. See https://github.com/atom-haskell/ide-haskell/issues/99 for background and discussion. There are a few other reasonably convenient options for showing type/info/etc.

**Comment by vasily-kirichenko** [comment]
@lierdakil I see, thanks. It makes sense. 

What I actually need is to show tooltip without touching the mouse, by a key binding, like `Ctrl+Q`. I've tried to google if it's possible, but failed. Maybe you know a way?

**Comment by lierdakil** [comment]
See https://github.com/atom-haskell/haskell-ghc-mod#keybindings. Some of the relevant keybindings I personally use:

```cson
"atom-workspace.ide-haskell":
  "ctrl-shift-b": "ide-haskell-cabal:build"
  "ctrl-shift-t": "ide-haskell-cabal:test"
"atom-text-editor[data-grammar~=\"haskell\"]":
  "ctrl-alt-I": "haskell-ghc-mod:insert-import" # i.e. ctrl-alt-shift-i
  "ctrl-alt-t": "haskell-ghc-mod:show-type"
  "ctrl-alt-i": "haskell-ghc-mod:show-info"
  "ctrl-alt-T": "haskell-ghc-mod:insert-type" # i.e. ctrl-alt-shift-t
  "ctrl-alt-.": "ide-haskell:next-error"
  "ctrl-alt-,": "ide-haskell:prev-error"
```

Also there's an option to show type/info/both on selection in haskell-ghc-mod settings (which I personally don't like, but YMMV):
![image](https://cloud.githubusercontent.com/assets/7275622/18379981/ea039c30-767d-11e6-8338-d2765f6e1adf.png)

Might be a good idea to disable tooltips on mouseover if you don't want those.

F.ex.
![image](https://cloud.githubusercontent.com/assets/7275622/18379924/a3b46228-767d-11e6-9da7-ca3a2e682393.png)
<...>
![image](https://cloud.githubusercontent.com/assets/7275622/18379892/7d250fb8-767d-11e6-9598-a13c94980ce4.png)
<...>
![image](https://cloud.githubusercontent.com/assets/7275622/18379902/8afd4c22-767d-11e6-9ffe-591c74edb8c7.png)

**Comment by vasily-kirichenko** [comment]
Oh, man, it's awesome! Thanks a lot. Now I'm the happiest Haskell newbie on Earth :)

**Comment by varosi** [comment]
@lierdakil, out-of-scope, but interesting - what is the plug-in to visualize => as single symbol in types that you have shown in screenshots above?

**Comment by vasily-kirichenko** [comment]
@varosi it's Fira Code (free) font + ligatures enabled in Atom settings.

**Comment by varosi** [comment]
Thanks! There is some problem under Windows and it doesn't work, but I'll fight with it.

**Comment by vasily-kirichenko** [comment]
it works on Windows as well for me (Hasklig font also works)
