### ISSUE TITLE
Size of last autocomplete panel's font is disproportional

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell#173]
![selection_005](https://cloud.githubusercontent.com/assets/873919/18503821/1059bd42-7a70-11e6-87a8-2b0f46204e12.png)

I think the font should be of the same size as the editor's.

**Comment by lierdakil** [comment]
Well, frankly that's just how it goes: completion hint panel is part of general UI, so it's font size is handled by Atom. You can always override this with a custom stylesheet, if you need to, but I don't think it's possible to tie its font size to editor's without some rather unsightly hacks.

Set from stylesheet:

```less
atom-text-editor[mini][data-grammar="hint haskell"] {
  font-size: 1px;
}
```

This obviously won't scale with editor though.

I might consider adding an optional hack to grab font size from editor config, but I'm *extremely* pressed for time right now, so this will have to wait. PRs are always welcome.

**Comment by lierdakil** [comment]
Sorry, referenced wrong issue in commit. As I said, pressed for time...

**Comment by lierdakil** [comment]
Moved to relevant repo
