### ISSUE TITLE
Errors appear on the Panel for a fraction of second, then gone

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell#174]
When I save the file with `Ctrl+s`, the error appears for a short period of time:

https://youtu.be/-iCt279FNEU

Errors should be shown until there are no one in the project.

**Comment by vasily-kirichenko** [comment]
It's done after restarting Atom, so it seems to be an Atom bug, not ide-haskell.

**Comment by lierdakil** [comment]
It might be an ide-haskell bug, but without clear reproduction steps, it
will be extremely hard to track down and fix. I don't think it surfaces
often though, so I would hope that an occasional Atom restart isn't too
much of a burden. If it's somehow related to ide-haskell, it is bound to be
fixed eventually during a code review or a refactoring spree (although new
bugs might be introduced, but that's just how it is -- as sad as that might
be)

2016-10-01 19:55 GMT+03:00 Vasily Kirichenko <notifications@github.com>:
