### ISSUE TITLE
Feature Request - Synopsis Similar to Bookmark Search Dialogue

### ISSUE THREAD

**Issue by theGhostJW** [atom-haskell/ide-haskell#177]
It would be great to have a keyboard bindable way to invoke a dialogue similar to the bookmark list you get with <alt><F2> showing declarations in the file - functions, type classes / aliases etc.

When the this dialogue was active it could be progressively filtered like the bookmarks dialogue and keyboard shortcut could toggle the order of list entries between case insensitive alphabetical and the order the entries appear in the file . The default could be set by config or persisted between invocations of the dialogue.

**Comment by lierdakil** [comment]
Well, for one, there's symbols-view package, which will allow jumping between function type annotations. Then there's ide-haskell-hasktags, which is intended as a Haskell-specific drop-in replacement for symbols-view...  although it's an alpha, but it works fine most of the time. So overall, I'd say this use-case is covered. If you want something changed in ide-haskell-hasktags, feel free to file issues on that package.

**Comment by theGhostJW** [comment]
Sounds good thanks
