### ISSUE TITLE
Prettify doesn't work for .hsc files

### ISSUE THREAD

**Issue by SX91** [atom-haskell/ide-haskell#181]

**Comment by lierdakil** [comment]
Sorry about the late reply, I missed the notification.

Prettify is not designed to work on anything but plain old Haskell, and I sincerely doubt stylish-haskell or hidnent will parse hsc2hs files correctly, f.ex. https://github.com/jaspervdj/stylish-haskell/issues/79

**Comment by cblp** [comment]
See also #216
