### ISSUE TITLE
GHC errors have more empty new lines than needed on Windows

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell#183]
Atom shows it like that:
![ghcerror](https://cloud.githubusercontent.com/assets/6051718/21849916/db09acd4-d810-11e6-886a-389e62ee3d0d.png)

But when I build it from Windows Console - it's alright without such empty new lines.
I'm using latest Atom + atom-haskell plug-ins on Windows 10.

**Comment by varosi** [comment]
Hints about errors contain empty lines, too.

**Comment by lierdakil** [comment]
Is this specific to builds, and not happening with ghc-mod powered checks? If so, ide-haskell-cabal is probably the culprit.

**Comment by lierdakil** [comment]
Try updating to ide-haskell-cabal v1.7.2 to see if it helps any.

**Comment by varosi** [comment]
Great! It's alright now! Thanks a lot!
