### ISSUE TITLE
Deprecated selector in `ide-haskell/styles/ide-haskell.atom-text-editor.less`

### ISSUE THREAD

**Issue by clojj** [atom-haskell/ide-haskell#184]
In `ide-haskell/styles/ide-haskell.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration:before` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration:before`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-lint` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-lint`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-lint:before` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-lint:before`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-warning` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-warning`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-warning:before` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-warning:before`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-error` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-error`

* `.gutter[gutter-name="ide-haskell-check-results"] .decoration.ide-haskell-error:before` => `.gutter[gutter-name="ide-haskell-check-results"] .syntax--decoration.ide-haskell-error:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lierdakil** [comment]
All should be good now.

**Comment by haroldtreen** [comment]
Thanks for the quick fixes @lierdakil ! 👍

**Comment by clojj** [comment]
Thanks!
