### ISSUE TITLE
support for tests in ide haskell

### ISSUE THREAD

**Issue by miladz68** [atom-haskell/ide-haskell#188]
I write my tests in /tests folder next to /src folder and setup .cabal file as : 

`Test-Suite test-melody`
 ` type:               exitcode-stdio-1.0`
  `main-is:            MainTest.hs`
  `hs-source-dirs:     test`
  `build-depends:      base >=4.9 && <4.10,`
  `                    --test-framework,`
   `                   --test-framework-hunit,`
 `                     HUnit,`
  `                    containers == 0.5.*`

Now when in every test file when I import from HUnit I get a red warning that the interface is part of a hidden package. In general the interface for all test dependencies are not recognized by atom.

How can I fix this ?

**Comment by miladz68** [comment]
running the following commands solved my issue

```
$ cabal configure --enable-tests
$ cabal build
$ cabal test
```

**Comment by lierdakil** [comment]
Glad to hear you solved it.

пн, 23 янв. 2017 г. в 14:42, milad <notifications@github.com>:
