### ISSUE TITLE
Unicode substitution for display of notation

### ISSUE THREAD

**Issue by prb** [atom-haskell/ide-haskell#19]
See, e.g., what Emacs does: http://haskell.github.io/haskell-mode/manual/latest/#Unicode

**Comment by lierdakil** [comment]
Would it be agreeable to leverage autocompletion for this?

**Comment by lierdakil** [comment]
Actually, this is something for the scope of language-haskell, since it's basically snippets. So when (if) I'm able to push language-haskell to atom.io, this will be there.

I'll close this as wontfix now.
