### ISSUE TITLE
atom throws error for wrong version in ide-haskell

### ISSUE THREAD

**Issue by andrewufrank** [atom-haskell/ide-haskell#193]
it says that i have installed 1.13.1 and should have 1.14.3

i have installe 1.9.4, which is according to the web page, the latest version. there is no 1.14.4 neither 1.13.1.
something seriously wrong?  the error occurs if i try to set the build target.

**Comment by lierdakil** [comment]
I believe it complains about Atom version, not ide-haskell version... In any case, post error log here so I could take a look.

**Comment by andrewufrank** [comment]
thank-you - update did not indicate that a new version of atom is available. i installed it and hope this fixes some of my errors.
it would be useful to fix the error message to indicate which piece to update
