### ISSUE TITLE
Annoying auto-ident behavior when pasting code

### ISSUE THREAD

**Issue by jhrcek** [atom-haskell/ide-haskell#202]
When I want to paste some code (using Ctrl+V) the editor does not take the current cursor's position into consideration. Instead it indents the pasted code below previous definition.

Steps to reproduce: 
Write a function with some indented code like
```
f :: Int
f = g 0
  where
    g x = x + 1
```

Then copy it and paste it below the definition, making sure the cursor is in the first column below the definition before pressing Ctrl+V.
Actual behaviour: the pasted definition is indented below g of previous definition
Expected behaviour: the pasted definition begins where I placed the cursor.

Would it be possible to let the code be pasted where my cursor was without indenting it (which is the most intuitive behaviour you get in most other text editors)?

![annoyinautoindent](https://cloud.githubusercontent.com/assets/2716069/24286930/a4b234f4-1077-11e7-8124-714c21323f6c.png)

**Comment by lierdakil** [comment]
Not really related to ide-haskell package, but oh well...
![image](https://cloud.githubusercontent.com/assets/7275622/24287813/2cb5034a-108c-11e7-9797-da9f30d619a1.png)

**Comment by jhrcek** [comment]
Oh, so that was the cause :-) Thanks for the tip. I'm closing the issue.
