### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by karljs** [atom-haskell/ide-haskell#207]
Is there a particular reason that there has not been a stable release in 5 or so months?  It seems that you have done a ton of work in that time and it's a shame that the majority of users are not benefitting from it!

**Comment by lierdakil** [comment]
Well, first there was little to release, then there were some blockers, and for the last month or so I was just waiting for Atom 1.19 to drop. Which just happened yesterday. So there you go, everything released, and now I will probably drown in bugreports, because *something* is defenitely broken.

**Comment by karljs** [comment]
Thank you for all of the hard work on this.
