### ISSUE TITLE
Installed OK but no functionality

### ISSUE THREAD

**Issue by grahamh** [atom-haskell/ide-haskell#21]
Sorry I have probably done something wrong, but cant seem to get this to work.

I have followed the installation instructions and I have a directory with a Haskell file and a CABAL project. When I load the directory the ide-haskell menu pops up so I think it is recognising the project. However, there is no syntax highlighting and Haskell is not available as an option if I click on the plain text link at the bottom right.

The toggle panel option of the menu works but all the other options seem to do nothing. Not even displaying an error to say it can't find ghc-mod for example.

I am guessing I have made a stupid mistake, but can't see it.

Any ideas?

I am running on windows 7

TIA,

Graham

**Comment by gitfoxi** [comment]
For me this came down to environment variables. I'm on os x but i imagine it's the same for other platforms. If i launch Atom from the spotlight that it doesn't have the environment variables that are in my terminal. So it doesn't even know the path for GHC. If i launch it from the terminal then everything is just fine.
