### ISSUE TITLE
Using `linter` for displaying errors

### ISSUE THREAD

**Issue by Kwarrtz** [atom-haskell/ide-haskell#211]
I'm not a huge fan of the current `ide-haskell` output panel and would prefer it if the package would use the `linter` interface for displaying error messages, both to decrease clutter on my screen and to be more consistent with my set-ups for other languages. Looking at [this page](https://atom-haskell.github.io/core-packages/ide-haskell/) it seems that something approaching this functionality can be achieved by setting the `messageDisplayFrontend` parameter in the package settings. However, I haven't been able to find any such parameter. Am I missing something? Or is the documentation out of date? If it is, is there another way to achieve the same result? And finally, if not, can such a feature be added?

**Comment by lierdakil** [comment]
![image](https://user-images.githubusercontent.com/7275622/29741226-449c5b0c-8a71-11e7-8691-aed8b96e1973.png)
...
![image](https://user-images.githubusercontent.com/7275622/29741228-550c1b6c-8a71-11e7-9c16-a039aea87818.png)

NB: you need Atom 1.19

**Comment by Kwarrtz** [comment]
Ah, thank you, that seems to have fixed the issue. I didn't even realize it was out of date.
