### ISSUE TITLE
Not finding System.Random

### ISSUE THREAD

**Issue by AndrewC19** [atom-haskell/ide-haskell#220]
When using the IDE-Haskell, if I use an import such as import System.Random, I get an error:

Failed to load interface for `System.Random'
Use -v to see a list of the files searched for.

However, if load the module directly in ghci it works as expected.

Any ideas why?

**Comment by lierdakil** [comment]
So, any luck?

**Comment by AndrewC19** [comment]
In the end no, reverting back to ghc 8.0.2 seemed to cause other issues. Just have to stack exec atom for now!

**Comment by lierdakil** [comment]
Okay. Just be aware that building with cabal will likely fail -- cabal will complain about `GHC_PACKAGE_PATH`.

**Comment by dmotz** [comment]
Any advice on fixing this?

**Comment by lierdakil** [comment]
@dmotz, the most common reason for this is a missing package in the cabalfile build-depends.
