### ISSUE TITLE
Support for larger project with multiple yaml files

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell#221]
An option to select which Stack YAML file to be used for all Stack operations. Usually different files are used for different LTSes or different OSes. Our project is multi-yaml file and currently cannot be built in ide-haskell.

**Comment by lierdakil** [comment]
This was on my TODO list for a while, but I didn't manage to get to it yet. As a kind of a workaround, setting `STACK_YAML` environment variable either before starting Atom, or from console with `process.env.STACK_YAML='...'` works well enough.

**Comment by varosi** [comment]
Great! 10x!
