### ISSUE TITLE
Toggle panel usability issue with ide-haskell-repl

### ISSUE THREAD

**Issue by razvan-panda** [atom-haskell/ide-haskell#224]
When moving mouse to click at the beginning of the repl the toggle button expands up and prevents clicking. This is mainly an issue when there is already something typed in the repl text box. The issue happens by default because when the repl is opened it occupies exactly half the screen and that is where the toggle panel button is also.

![](https://i.imgur.com/HfESrCx.png)

**Comment by lierdakil** [comment]
Yeah... that's Atom's thing though. Not much I can do about it.

**Comment by razvan-panda** [comment]
This actually seems to be an issue only when moving the mouse pointer from the pane upwards. But still it is quite confusing.

**Comment by razvan-panda** [comment]
@lierdakil Ah, I see what you mean, those things are all over the place :)
