### ISSUE TITLE
Opened Atom on a new folder -->  "Haskell IDE" gone from the main menu

### ISSUE THREAD

**Issue by Muzietto** [atom-haskell/ide-haskell#229]
I am a web developer and I use Atom since a few years; for my pet Haskell projects I used it only as dumb file editor, while all the rest of the work done from the shell. Now I am trying for the first time ide-haskell with all its related packages, in order to have a more straightforward development. 

Unfortunately I have a major issue:

 - I installed all the needed packages with Atom opened on the folder of an older Haskell project. Everything went fine and the "Haskell IDE" item appears in the Atom menu. Every ide-haskell feature seems to be working.

 - If I open Atom on the folder of a new Haskell project I created this morning with 'stack new', the "Haskell IDE" item has disappeared from the Atom menu. No functionality is available. The packages are still installed, but apparently they do no nothing

How can I ensure that opening Atom on any folder will enable the Haskell IDE functionalities?

**Comment by lierdakil** [comment]
`ide-haskell` and friends are not activated until you open a Haskell or Cabal file in the editor. This is done to conserve resources when you don't want a Haskell IDE running. Atom does not offer a straightforward ability to write custom activation triggers, hence it activates on grammar usage.

Hopefully this explains things.

**Comment by bjornbm** [comment]
It may ber worth noting that nowadays `stack new` does not (I believe) create a Cabal file. I generates only a `package.yaml` file which in turn is used to generate a Cabal file when you use `stack build` (and/or other commands).
