### ISSUE TITLE
Checking and linting not working with Cabal 1.22.0.0

### ISSUE THREAD

**Issue by sbeschke** [atom-haskell/ide-haskell#31]
Precisely, what seems to matter is the version of Cabal which configured the project directory.

From a clean package base:

```
~/project$ cabal install cabal-install-1.20.0.6 -j
~/project$ cabal install ghc-mod-5.2.1.2 -j
~/project$ cabal clean && cabal configure
~/project$ atom
```
At this point, if I produce syntax errors in a source file, I get error messages as expected.
```
~/project$ cabal install cabal-install-1.22.0.0 -j
~/project$ atom
```
Behaviour remains functional as expected.
```
~/project$ cabal clean && cabal configure
~/project$ atom
```
Now it is impossible to produce error / warning / lint messages for this project.

Reverting back to cabal-install-1.20.0.6 and reconfiguring fixes the problem.

The bug occurs independently of the project, including on a minimal Hello World project.

**Comment by UltraSabreman** [comment]
I can confirm that this is the case.

**Comment by lierdakil** [comment]
This is likely ghc-mod issue. Try running ghc-mod check \<source-file.hs> in your project directory.

**Comment by edsko** [comment]
Yes, this is a problem with `ghc-mod` https://github.com/kazu-yamamoto/ghc-mod/issues/417.

**Comment by lierdakil** [comment]
Okay. There's a guide on how to fix this [here][1]. Since this is not a bug with ide-haskell, I'll mark this as invalid, but leave it open so that anyone experiencing this could see solution.

[1]: https://github.com/kazu-yamamoto/ghc-mod/wiki/InconsistentCabalVersions

**Comment by pmlodawski** [comment]
@lierdakil link you provided is dead

**Comment by lierdakil** [comment]
Final resolution for this issue is "use ghc-mod 5.4.0.0 or above", and I think this can be closed.
