### ISSUE TITLE
Enable ide-haskell on standalone .hs files

### ISSUE THREAD

**Issue by mlacorte** [atom-haskell/ide-haskell#46]
When I'm prototyping something in Haskell, I like doing it outside of a Cabal project so that I don't have to worry about managing the .cabal file while I'm trying out different libraries and moving code around a lot. Could you add a feature that if no Cabal project is detected, ide-haskell would treat the file as a standalone Haskell file and operate appropriately?

**Comment by rhvall** [comment]
I totally agree with @mlacorte, it took me a while to realize that the ```ide-haskell``` functionality is only enabled when a ```cabal```` project structured is recognized, whereas I was testing only with a standalone file. What would be needed to support single Haskell files??

**Comment by lierdakil** [comment]
Fixed in 0.5.0
