### ISSUE TITLE
Use ghc-modi for performance

### ISSUE THREAD

**Issue by altaic** [atom-haskell/ide-haskell#5]
As has been noted in ghc-mod (https://github.com/kazu-yamamoto/ghc-mod/issues/253) and ghcmod-vim (https://github.com/eagletmt/ghcmod-vim/issues/48), using ghc-modi rather than ghc-mod has the benefit that results are cached a la hdevtools.

It may be worthwhile to go the same route: start a ghc-modi process when a project is opened, pass queries to it while the project is open, parsing the results, and close the process when the project closes.

**Comment by lierdakil** [comment]
Fixed in 0.5.0
