### ISSUE TITLE
prettify-file moves cursor to the end of the buffer

### ISSUE THREAD

**Issue by kRITZCREEK** [atom-haskell/ide-haskell#58]
I think it should remember the cursor position

**Comment by lierdakil** [comment]
This might be a little bit challenging, since buffer *changes* in the process, but I'll see what I can do.

**Comment by kRITZCREEK** [comment]
Ye i thought about that aswell but lookign at the emacs haskell-mode implementation shows that they don't account for the changing file either:

https://github.com/haskell/haskell-mode/blob/728924c9d1b464c2bcec72719e5bc401f0bfcce6/haskell-commands.el#L789
