### ISSUE TITLE
Insert type signature

### ISSUE THREAD

**Issue by joozek78** [atom-haskell/ide-haskell#59]
It would be cool to have a command to insert signatures for existing functions.
Before:
```
main = print "cool"
```
After:
```
main :: IO ()
main = print "cool"
```

It would help a lot, since top-level bindings has to be explicitly typed (at least in my code). I think that implementation shouldn't be too worrisome - just get type for expression and insert it

**Comment by lierdakil** [comment]
In fact, there is. Docs are lagging behind a bit. Quick instructions follow.

### Lazy test

Put text cursor on function name that you want to insert definition for. Right-click on editor (or whatever brings out context menu), and select Haskell IDE → Insert Type. Type should be inserted into the line above first definition.

I couldn't find a way to get point from which context menu was called (yet?), so you *have* to put text cursor on function name.

### Involved (and recommended) option

The command is called `ide-haskell:insert-type`, and there are two ways you can assign a keybinding for it.

Easier one (and recommended) is to open ide-haskell settings and find `Hotkey Insert Type`. Put any key combination you want. Modifier keys are written with dash separator, and if you want `shift`, it's probably better to capitalize letter. For example: `ctrl-alt-T` would bind to `Ctrl+Alt+Shift+t`.

Harder one relies on Atom way of assigning keybindings. Add the following into your `keymap.cson`:

```cson
'atom-text-editor[data-grammar~="haskell"]':
  'ctrl-alt-T': 'ide-haskell:insert-type'
```

Obviously you can change `ctrl-alt-T` to anything you want.

**Comment by lierdakil** [comment]
So... can I close this?

**Comment by joozek78** [comment]
Sure
