### ISSUE TITLE
[Type popup Flickerring] mouse move trigger type popup reload even when mouse remains on same word or same selection

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#62]
Mouse move trigger type popup reload even when mouse remains on same word or same selection
The flickering makes type popup hard to read.
I'm on a mac, latest atom version 0.204.0

**Comment by lierdakil** [comment]
Sorry, does this happen when mouse *moves*, or even if it's stationary?

Current implementation should only hide popup if mouse moved to different *character*, so a little bit of "shivering mouse" should be fine. If that's not the case, well... I'm not sure what's going wrong.

If you just want alternative behavior, sure, that's doable. But I'd ask you to explain what alternative behavior should actually be, in your opinion.

**Comment by rvion** [comment]
Thanks for your reactivity ! :+1: 

Indeed, popups disapears when the mouse move from one char to another.
Though, on my mac, the refresh delay is high enough for the flickering to truelly be annoying

Here are a few ideas to improve the current status:

  - If some text is selected, and if the mouse is over the selection, then no need to refresh the popup
  - if mouse move from one char to an other, if both are from the same word (let's assume consecutive a-zA-Z0-9), no need to refresh
  - if mouse move from one char to an other, an other alternative could be to simply wait for the new type to be available before redrawing the popup

**Comment by lierdakil** [comment]
Actually, that last point seems very reasonable, and might actually be enough to reduce visual annoyance. And I think it's very straightforward to implement as well.

**Comment by rvion** [comment]
minor update: looking at cpu consumption :racehorse:, 1. and 2. might worth the extra work later

**Comment by lierdakil** [comment]
If you're using ghc-modi, then cpu consumption should be reasonably low, since result if cached.

**Comment by rvion** [comment]
Is haskell-ide using ghc-modi over ide-backend for type info ?

From what I know, ide-backend is superior in terms of features, and is able to expand type expression, with is really super usefull in many circumstances: 

![screen shot 2015-05-28 at 22 57 51](https://cloud.githubusercontent.com/assets/2150990/7870956/0a23b7a6-058d-11e5-9341-6dcfe8c6c4d8.png)

An other advantage I noticed from experience is that ide-backend have a more clever way to identify expressions when only a subpart is selected.

**Comment by lierdakil** [comment]
Well, the need to install `haskell-ghc-mod` package should have tipped you on what `ide-haskell` is using :smile:  Truth be told, I had no luck with setting up ide-backend, ghc-mod seems much more compatible. Anyone interested is free to implement other backends though. Since `ide-haskell` is just a frontend package, backend implementation should be pretty straightforward. Consult https://github.com/atom-haskell/haskell-ghc-mod for backend interfaces, if interested.

I have to say that ide-backend implements autocompletion very poorly though. Context-sensitivity is almost nonexistent, which is really unfortunate IMO.

**Comment by rvion** [comment]
@lierdakil : yep, just saw that :)
![screen shot 2015-05-28 at 23 11 28](https://cloud.githubusercontent.com/assets/2150990/7871249/fc161f76-058e-11e5-8f02-fa39be60297b.png)

I have been fooled by:
![screen shot 2015-05-28 at 23 12 56](https://cloud.githubusercontent.com/assets/2150990/7871268/206cc78a-058f-11e5-88a7-4006137f6da8.png)

**Comment by rvion** [comment]
I had both ide-backend and ghc-mod already installed, so I didn't pay attention.
Also, I guess you're right in that ghc-mod is still more mature and compatible for now.
Thanks for all those infos :)

**Comment by lierdakil** [comment]
Well, "ide-backend" is a very generic name, so some confusion is bound to happen. Back on topic, I think I implemented (3) to a satisfactory degree, which should help until a more sophisticated fix is available. I'll push shortly.

**Comment by lierdakil** [comment]
Finally got around to finishing this up.

Caveat: implementation relies heavily on language-haskell to detect separate tokens, so if highlighting goes haywire, so will the mouseover tooltips =\
