### ISSUE TITLE
[Type popup] when moving mouse fast, popup lags with increasing delay

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#63]
### Currently:

Atom send type queries to ide-backend for each char hovered, without waiting for the previous one to finish.
if mouse move faster than type query, requests queue up.

problem: popups successfully appears on useless places, following mouse with increasing delay (easilly ~2+ sec on my mac when moving normally my mouse over large code)
Not only it's not efficient, but it's also weird :)

### normal behaviour

There is 2 things to fix:

  1. Send only one query max, and keep one ready to be sent next, after the previous have returned. Instead of queuing requests, if mouse keep moving while previous request is pending, only the next query to run should be updated.

  2. When the ide-backend finally return type information, atom should check if the mouse is still hovering the requested char (or word, see #62 ) and only display the popup if so.

Any opinion on above sentences ? :)

**Comment by lierdakil** [comment]
This sounds reasonable, but will take some time to implement. For now, you can increase `Expression Time Interval` configuration parameter (open `ide-backend` package settings, it should be somewhere near the top)

**Comment by rvion** [comment]
Thanks ! :)

btw, no units are specified in label above (I guess it's ms)
![screen shot 2015-05-28 at 23 17 44](https://cloud.githubusercontent.com/assets/2150990/7871405/ec80d604-058f-11e5-8504-7b0d9b5b0be4.png)

**Comment by lierdakil** [comment]
Yes, it's ms. I should probably update description to make that clear.

**Comment by lierdakil** [comment]
I just published v0.5.7 with your suggestions implemented to some degree (see changelog for more information). If you could verify, that'd be great. Thanks.

**Comment by rvion** [comment]
:+1: Awesome.
I checked v0.5.7 and it works great
