### ISSUE TITLE
Add `cabal` commands, like `build` and `test` to IDE menu/save triggers

### ISSUE THREAD

**Issue by Quantumplation** [atom-haskell/ide-haskell#66]
This would be, in my opinion, the single greatest feature that you could offer in the IDE.  My day job is a C# developer, and NCrunch is just a god-send.  Combine that with the awesomeness of quick check, and...

(If there's already an atom package that does this, I couldn't find it, i'd love to be pointed in that direction!)

**Comment by lierdakil** [comment]
Running QuickCheck relies on two cardinal assumptions:

a) You're willing to wait until it's done
b) You wrote specs

This makes it nigh impossible to run against WIP code in online mode.

If you have an idea on how to make it work, do tell.

**Comment by Quantumplation** [comment]
I don't see why this would be hard (then again, I'm not the one who's been working on this stuff, so you obviously know better than I would):

 - User presses save
 - Trigger compiler, if errors, display, if none, continue
 - Trigger linter, if warnings, display
 - Check for quickcheck specs (Is there some standard for identifying them?)
 - Start a quickcheck run
 - User continues to edit
 - When quickcheck run finishes, if there were failed tests, display them, otherwise, be silent.

The user only really needs to see *if* there was an issue, and there's no reason he has to wait for them to run.

Something even cooler, that seems like it should be possible, if difficult, would be to maintain the AST of the program, and diff it when you save, find any types / functions that you've changed, follow them up the call tree, and then only run specs that invoked that code.

**Comment by kRITZCREEK** [comment]
@Quantumplation You would usually set up a Test-Suite in your cabal project and run that. 
 see: http://stackoverflow.com/questions/20331209/haskell-unit-testing
But that's not the task of a syntax checker. And I think it would take way too long for the syntax checker of IDE Haskell.

It would however be a nice addition to be able to run cabal commands. Maybe that's the feature request you're looking for?

**Comment by Quantumplation** [comment]
This project is called ide-haskell, not syntax-checker-haskell ;)  However, if being able to run cabal commands achieves that, then yea, no need to reinvent the wheel :P

**Comment by lierdakil** [comment]
Parsing Haskell is *hard*, even when using GHC API (which is not really an option with coffeescript anyway, unless you're OK with several-megs-large script files)

I didn't really *think* about adding `cabal` commands to the mix, but I guess that's reasonable request for IDE. I guess `build` and `test` should be enough, as a start. Not a feature I'm personally looking for (I just use `terminal-panel` for this), but useful I guess.

I'll rename this issue accordingly.

**Comment by lierdakil** [comment]
Implemented with `ide-haskell-cabal` and v0.8.0.
