### ISSUE TITLE
Ide-haskell cannot find backend provider (haskell-ghc-mod)

### ISSUE THREAD

**Issue by jannickj** [atom-haskell/ide-haskell#68]
So I decided to update my ide-haskell from version 0.3(something). 
However after doing so nothing seems to work.
I get the message about missing haskell-ide-backend, everytime I restart it. Which I am assuming is the reason why it doesn't function.

Also haskell-ghc-mod does not appear as a backend provider in the settings.

My setup:
Windows 7
GHC 7.8.3
cabal-install version 1.20.0.3
Atom 0.183
 autocomplete-haskell 0.4.3
 autocomplete-plus 2.7.1
 haskell-ghc-mod 0.7.5
 ide-haskell 0.5.10
 keyboard-localization 1.4.1
 language-haskell 1.0.0
 merge-conflicts 1.3.1

For cabal packages:
ghc-mod version 5.2.1.2 
ghc-modi version 5.2.1.2
stylish-haskell-0.5.11.1

**Comment by lierdakil** [comment]
For the love of all that is holy, please, *please* update Atom.

**Comment by jannickj** [comment]
Oh I thought it was the newest version because atom told me so :p

**Comment by lierdakil** [comment]
Also note that autocomplete-plus is now bundled with Atom. I think update is handled automatically, but check that "custom" version is uninstalled properly.

**Comment by jannickj** [comment]
Thank you, I don't get why atom version continues to fool me. Next time I'll manually check the atom website before I make an issue :p

**Comment by jannickj** [comment]
Anyway. Updating atom solved the problem so I'll close the issue.

**Comment by lierdakil** [comment]
Ok, great.
