### ISSUE TITLE
Filter warnings based on the file that is currently in view

### ISSUE THREAD

**Issue by jannickj** [atom-haskell/ide-haskell#70]
As it stands right now I get warnings from everywhere in my project not just the file I am checking. I don't know if it's a feature or a bug. But personally I'd prefer only getting warnings from the file I am checking.

Could be Windows OS related (file paths messing up) but I am pretty sure I was getting the same on my arch linux.

However my personal guess is ghc-mod provides incorrect information which isn't checked.

**Comment by lierdakil** [comment]
That would be a feature. You can click on filename in warning list to open it in Atom at a place that generated a warning. Note, however, that only current file and its imports are checked, not a whole project.

I could implement a filter, but I'm more than a little bit busy lately, so this might have to wait for a week or two.

**Comment by jannickj** [comment]
Yeah no rush I just wanted it to point it out, because it seemed off to me.

**Comment by lierdakil** [comment]
There is a switch for this in v0.8.0

**Comment by jannickj** [comment]
Awesome!
