### ISSUE TITLE
Uncaught TypeError: Cannot read property 'containsPoint' of undefined

### ISSUE THREAD

**Issue by MichaelRalston** [atom-haskell/ide-haskell#73]
1. This happens for me when I run 'check' on Haskell code with errors, then double-click on the line in the output panel to go there in order to fix it. Afterwards, the actual editing pane of atom is fully non-interactable and I have to quit and restart.

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.5.11

### Stack Trace

Uncaught TypeError: Cannot read property 'containsPoint' of undefined

```
At C:\Users\sotek\.atom\packages\ide-haskell\lib\editor-control.coffee:138

TypeError: Cannot read property 'containsPoint' of undefined
    at C:\Users\sotek\.atom\packages\ide-haskell\lib\editor-control.coffee:235:23
    at Array.filter (native)
    at EditorControl.showExpressionType (C:\Users\sotek\.atom\packages\ide-haskell\lib\editor-control.coffee:234:14)
    at C:\Users\sotek\.atom\packages\ide-haskell\lib\editor-control.coffee:79:26
```

### Commands

```
     -0:22.4.0 application:add-project-folder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:15 ide-haskell:check-file (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.4
haskell-ghc-mod, v0.7.5
ide-haskell, v0.5.11
language-haskell, v1.1.1
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Thanks for reporting. Hopefully fixed in 0.5.12. If not, feel free to reopen.
