### ISSUE TITLE
open documentation for word

### ISSUE THREAD

**Issue by miguel-negrao** [atom-haskell/ide-haskell#77]
preferably using local documentation, or one command for  local docs and another command for for hackage web site.

**Comment by lierdakil** [comment]
https://atom.io/packages/ide-haskell-hoogle does support some of this via hoogle. It's still very early alpha, and it's not context-aware, so it can't guess what package a given symbol came from at the moment, but it's better than nothing, I think.

I'm closing this for now; If there are other suggestions, or you found a bug, feel free to open new issues on relevant repositories.
