### ISSUE TITLE
Request: Hotkeys for "Go to next error" and "Go to previous error"

### ISSUE THREAD

**Issue by edsko** [atom-haskell/ide-haskell#79]
(As discussed previously.)

**Comment by lierdakil** [comment]
Okay, I've slapped something together, but to do this properly, whole output-view needs a makeover (or even a facelift). Reason is, it's legacy code that I never got around to looking at very closely, let alone fixing.

You can see (and test) current work at [next-prev-error](https://github.com/atom-haskell/ide-haskell/tree/next-prev-error) branch. It's hackish, fragile, but should work for most cases.

**Comment by edsko** [comment]
Ok, excellent, using this branch now. Will let you know if any immediate difficulties arise.

Something we may want to think about for the future is highlighting the currently active error (either when you click on it or when you say go-to-next-error.

**Comment by lierdakil** [comment]
Sounds reasonable. When I get around to rewriting output-view I will take that idea into consideration.

**Comment by edsko** [comment]
Also, while we're at it, go-to-next-error should actually scroll to that error.

**Comment by lierdakil** [comment]
Sorry about the hold-up, I desperately needed some sleep after pulling an all-nighter. I've slapped together scroll-to-error, in the same hacky fashion. I will hold off on highlighting until code is a little bit more maintainable.

**Comment by edsko** [comment]
Hah, no worries! Your response time is rather impressive in fact :)

**Comment by edsko** [comment]
Should I still use the `next-prev-error` branch?

**Comment by lierdakil** [comment]
Yes, I pushed there. I'm a little bit reluctant to publish this code right now, since it can be very fragile.

**Comment by edsko** [comment]
Ok, no worries. I shall use it and report back.

**Comment by edsko** [comment]
Hmmm, just compiled a big project, and got 60 warnings (no errors), but the go-to-next and go-to-previous buttons are not working. If I activate the key binding resolver I see that when i press my shortcut the 'next-error' is activated, but it is greyed out and there is a cross before it. Not sure why this happened, and why it's happening now; I use go-to-next a lot and so far it was working -- not sure what is different about this case. (Perhaps it's the fact that there are only warnings and no errors? But I thought I'd had that before. Will keep an eye on it.)

**Comment by lierdakil** [comment]
Ide-haskell binds keys to editor with Haskell grammar, so that might be
related somehow. Other than that, no idea.
7 июля 2015 г. 13:34 пользователь "Edsko de Vries" <notifications@github.com>
написал:

**Comment by edsko** [comment]
Scrolling-to-error seems to work well though.
