### ISSUE TITLE
ide-haskell captures escape key always

### ISSUE THREAD

**Issue by edsko** [atom-haskell/ide-haskell#80]
For example, suppose we create a cursor spanning multiple lines, pressing escape should change the cursor back into a single line, but this doesn't happen because it gets caught by `ide-haskell:close-tooltip`.

**Comment by lierdakil** [comment]
Would changing default binding to `ctrl-esc` be a satisfactory solution?

**Comment by edsko** [comment]
For me, sure, but I don't know how many people would be affected by that (i.e., who rely on the current behaviour). Perhaps it would suffice for `ide-haskell` to capture the escape key when there is actually a tooltip visible? Either way is fine for me (but making escape unavailable to the rest of `atom` when `ide-haskell` is active is not :).

**Comment by edsko** [comment]
Ok, fantastic, this is great. 

(Sorry for reporting all these issues, but I write Haskell all day every every day so such things make a difference :)
