### ISSUE TITLE
"Could not find module ..." - ghc-mod ignores sandbox

### ISSUE THREAD

**Issue by jbracker** [atom-haskell/ide-haskell#81]
Hello,

I have installed haskell-ide, but I have two issues:

* I get no type information when I hover over expressions (I assume this is linked to my second issue)
* `ghc-mod` seems to ignore my cabal sandbox; I get the error "Could not find module ..." for every module outside of `base`

I checked if it is a issue with `ghc-mod` itself, but calling `ghc-mod check ...` on any of my haskell files works perfectly fine and delivers the expected results. Can you help me?

Versions:
* `ghc-mod` - [built from master to get it working with up-to-date cabal and ghc](https://github.com/kazu-yamamoto/ghc-mod/issues/437)
* `ghc` - 7.10.1
* `cabal` - 1.22.2.0
* `atom` - 1.0.0
  * ide-haskell - 0.6.2
  * haskell-ghc-mod - 0.8.1

EDIT: Here an example of the error messages I get:
~~~
/home/jbracker/.atom/home/jbracker/university/repos/research/proofs/polymonad-plugin/src/Control/Polymonad/Plugin/Graph.hs: 22, 8
Could not find module ‘Control.Polymonad.Plugin.Constraint’
Use -v to see a list of the files searched for.

/home/jbracker/.atom/home/jbracker/university/repos/research/proofs/polymonad-plugin/src/Control/Polymonad/Plugin/Graph.hs: 20, 18
Could not find module ‘Outputable’
It is a member of the hidden package ‘ghc-7.10.1.20150630’.
Use -v to see a list of the files searched for.
~~~

You can see that it doesn't even find other local modules and that the path it reports has the unusual prefix `/home/jbracker/.atom`, which it should not have.

**Comment by lierdakil** [comment]
Could you please enable 'Debug' option in haskell-ghc-mod settings and post console output when this happens here?
Also, what OS are you on?

**Comment by jbracker** [comment]
I don't know what changed, but I cannot reproduce the error anymore. Now everything works as expected. I kept using atom although the feature didn't work and at some point it just started to work. The weird errors do not come up anymore either. My best guess is that there might have been some old configurations lying around from my previous attempt at using atom for Haskell a few months ago.

I am under Ubuntu Trusty 14.04. I also tried it on another machine and had none of the described issues.

**Comment by lierdakil** [comment]
Probably ghc-mod was rebuilding cabal support module (`master` does that). It can take a while, but after that everything should work. Glad it resolved itself.

**Comment by ricardopieper** [comment]
I'm having that problem, but I think is ghc-mod's fault. When I run ghc-mod on console, it says:

    Warning: Could not find a component assignment, falling back to guessed GHC
         options.
    EXCEPTION: types:
           Could not find module ‘MyPackage’

The module exists, and `cabal build` runs just fine. The project compiles, proving that the module does exist. The project folder has a sandbox.

In the same project, there is another file with no imports (noy importing any of MY modules) that ghc-mod works fine. I don't know why yet, I should probably open an issue on the ghc-mod repository.

**Comment by lierdakil** [comment]
@ricardopieper, this is different (kind of). Opening an issue on ghc-mod repo is a good idea.
