### ISSUE TITLE
Stack support

### ISSUE THREAD

**Issue by xavier83** [atom-haskell/ide-haskell#82]
https://github.com/commercialhaskell/stack

When in a project directory configured using stack.yaml I get this error

    launching operating system process `cabal configure` failed: cabal configure (exit 1)
    Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
    update' to download it.
    cabal: At least the following dependencies are missing:
    diagrams-cairo >=1.2,
    diagrams-gtk3 >=1.0.1.3,
    diagrams-lib >=1.2,
    gtk3 >=0.12.5.0,
    transformers >=0.2.0.0 && <0.4

**Comment by rvion** [comment]
+1.
there seems to be some activity in several places : https://github.com/ajnsit/ghc-mod/tree/stack-support

**Comment by xavier83** [comment]
This might be of some help.
* https://github.com/commercialhaskell/stack-ide

**Comment by edsko** [comment]
`stack-ide` is a renaming of `ide-backend-client` and is designed specifically to talk to `ide-backend`. It would definitely be useful when we wanted to have `ide-backend` support in Atom, but not for `ghc-mod`.

**Comment by lierdakil** [comment]
We can't do much about this here, until ghc-mod gets support for stack (or we switch to another backend altogether). If there is already work underway, then I see no immediate reason to try and hack something together.

**Comment by cdupont** [comment]
This would be extremely useful. Trying to compile packages with cabal is really difficult these times.

**Comment by xavier83** [comment]
stack support has landed on ghcmod - master.
now there is a `--with-stack` option that can be passed to ghc-mod.

**Comment by DanielG** [comment]
`--with-stack` doesn't actually enable the stack support it's just for bypassing the PATH search BTW.

**Comment by wolftune** [comment]
Working for me with Stack now, I think this can be closed

**Comment by xavier83** [comment]
There was a serious performance issue, the *type popover* takes too long to show up on stack projects. strangely it got fixed after updating atom. closing this issue :+1:

**Comment by AshtonKem** [comment]
As far as I can tell ghc-mod now supports stack, and I've successfully used stack+ghc-mod in other editors (like Emacs). Is it time to consider stack support for ide-haskell?

**Comment by wolftune** [comment]
@AshtonKem This isssue is closed. ide-haskell has supported stack for months.

**Comment by AshtonKem** [comment]
Then I was mislead by the documentation which states 

> Note that ide-haskell currently only supports cabal and does not yet support stack-based Haskell projects; for now we are only using stack to build the executables that ide-haskell depends on.

**Comment by wolftune** [comment]
Then it makes sense to make a PR or an issue for updating the docs
