### ISSUE TITLE
Could not fine module 'Parser'

### ISSUE THREAD

**Issue by CThuleHansen** [atom-haskell/ide-haskell#84]
(Newcome to Haskell)

My files are in the same folder:
Calc.hs
Parser.hs

Parser.hs contains: module Parser (parseExp) where
and Calc.hs imports it like: import Parser

It works fine when I use :load in ghci. 
I get the error: Could not fine module 'Parser' Use -v to see a list of the files searched for

Am I doing something wrong or?

**Comment by CThuleHansen** [comment]
As far as I can tell ghc-mod does not search in the local directory of the file

**Comment by lierdakil** [comment]
If there is `.cabal` file present, it does not, instead searching source directory, specified in cabal (`src` by default). If there is none, then it does.

**Comment by CThuleHansen** [comment]
There is not a cabal file present in that folder.

**Comment by lierdakil** [comment]
ghc-mod also traverses directory tree upwards to look for cabal file. So it can find cabal file not necessarily in the directory you run it in, but in upper ones as well.

**Comment by CThuleHansen** [comment]
So I have to create a sandbox or?

**Comment by lierdakil** [comment]
If there is a cabal file in upper project directories, that means you are working on a cabal project. If you're not, just move your sources somewhere else. If you do, just set it up like you would normally set up cabal project: put all module files to `src` directory, and don't forget to include all auxiliary modules in `other-modules`, and main module in `main-is` (that's not really required for ghc-mod to function, but is required for cabal).

Does that make sense?

**Comment by CThuleHansen** [comment]
Yes, except I am nowhere near any cabal projects, that is why I do not understand it.
It only searches in the default cabal location, not the current folder at all

Here is the result of -v: 
C:\source\nicta\ex_05\Calc.hs:3:8:Could not find module `Parser' Locations searched:   C:\Users\XX\AppData\Roaming\cabal\bin\Parser.hs   C:\Users\XX\AppData\Roaming\cabal\bin\Parser.lhs   C:\Users\XX\AppData\Roaming\cabal\bin\Parser.hs   C:\Users\XX\AppData\Roaming\cabal\bin\Parser.lhs
C:\source\nicta\ex_05\Calc.hs:2:8:Could not find module `ExprT' Locations searched:   C:\Users\XX\AppData\Roaming\cabal\bin\ExprT.hs   C:\Users\XX\AppData\Roaming\cabal\bin\ExprT.lhs   C:\Users\XX\AppData\Roaming\cabal\bin\ExprT.hs   C:\Users\XX\AppData\Roaming\cabal\bin\ExprT.lhs
.

**Comment by lierdakil** [comment]
Hmm. Seems like `ghc-mod` thinks it's being run from `C:\Users\XX\AppData\Roaming\cabal\bin\`, instead of `C:\source\nicta\ex_05\`. That's... weird. What version of ghc-mod do you use? And for that matter, what version of ghc?

**Comment by CThuleHansen** [comment]
Yes, it seems like ghc-mod is being invoked from it's default location, instead of from the folder with  the file. It works now if I invoke it manually from cmd.

I am using the newest ghc-mod (how do I see version?) and ghc 7.8.4 64 bit

**Comment by lierdakil** [comment]
I'm confused. How did you get verbose output from ghc-mod if you didn't run it from `cmd`?

**Comment by CThuleHansen** [comment]
I did, but I ran it from the wrong location... Sorry.. But I guess that is the problem in Atom

**Comment by CThuleHansen** [comment]
the plugin seems to be running ghc-mod from the wrong location

**Comment by lierdakil** [comment]
Okay. Try opening your entire source directory with Atom, instead of individual files. There is a bug https://github.com/atom-haskell/haskell-ghc-mod/issues/32, that can prevent individual files from checking or otherwise working. I'm a little hard-pressed for time, so haven't looked into it yet, but this may be related.

**Comment by lierdakil** [comment]
If it doesn't help, or I'm entirely wrong and you already do that, open haskell-ghc-mod settings, enable 'Debug' option, close Atom, then try opening/checking/whatever your file (`Calc.hs` I believe?). Then open dev. console (View -> Developer -> Toggle Developer Tools -> Console tab), and copy its contents here, this would help pinpoint the issue.

**Comment by CThuleHansen** [comment]
Ah okay. 
So if I open JUST THAT FOLDER in either mode, then it works.
If i open a parent folder or a different folder, then it does not work in either mode

**Comment by lierdakil** [comment]
If you run Atom with *another* project directory, or open parent directory, that's somewhat expected. There can be ways to rectify that with some heuristics, but heuristics tend to break more often than not, sadly.

Since Atom supports multiple directories per project, I don't think this is an issue. If you would argue otherwise, please open a feature request with proposed behavior.

I think I can close this particular issue.

**Comment by CThuleHansen** [comment]
Thank you very much for your time. I will open a feature request
