### ISSUE TITLE
Ensure single trailing newline on stylish-haskell

### ISSUE THREAD

**Issue by razvan-panda** [atom-haskell/ide-haskell#85]
When setting stylish-haskell to run on save with `On Save Prettify` and `Ensure single trailing newline` from `whitespace` package is disabled the file still gets a single trailing newline automatically added if it does not have one. The expected behaviour would be to not make any unnecessary change to the file.

**Comment by lierdakil** [comment]
`stylish-haskell` adds newline at the end automatically. If you believe this is an error, please raise an issue with upstream repo (https://github.com/jaspervdj/stylish-haskell). Personally, I don't think it is. It's been a long-standing practice to add a newline at the end of source files, and there are multiple reasons to do so, and no compelling reason not to.

**Comment by razvan-panda** [comment]
Thank you for the reply, I might raise an issue for stylish-haskell as you suggested.

The idea is that a tool should not impose a certain style to people using it, they should be able to chose  themselves what style to use (style has very little to do with reason). The entire codebase could already be styled without trailing newlines. Less useless newlines means less polution. And the tools should no longer be having problems with lack of trailing newline.
