### ISSUE TITLE
Feature request: Support ghc-mod from subdir

### ISSUE THREAD

**Issue by CThuleHansen** [atom-haskell/ide-haskell#86]
As a newcomer to Haskell I am doing a lot of 2-3 hs-files exercises, sometimes they take only 10 minutes. Therefore I have the following project structure:
nicta
---->ex_01
-------->ex.hs
-------->file1.hs
---->ex_02
-------->ex2.hs
-------->file3.hs
etc...

However I cannot use ghc-mod if I add the nicta folder to atom. I have to add ex_01, ex_02.

It makes atom tree view clutted very fast and it is a bit of a hassle to create a cabal sandbox for small exercises.

So it would be awesome if ghc-mod was executed based on the context of the file it checks

**Comment by lierdakil** [comment]
Should work with haskell-ghc-mod 0.9.1 and up.

**Comment by CThuleHansen** [comment]
Sweet, thank you!
