### ISSUE TITLE
ide-haskell doesn't seem to notice I added a package to build-depends

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell#87]
I don't know when this started happening but I just now wrote `import Control.Monad.State` to which I got the classic "member of a hidden package" message. I added mtl to my `build-depends` and installed/configured the project again. It builds with `cabal build` but ide-haskell still reports the same message

```
Could not find module `Control.Monad.State'
It is a member of the hidden package `mtl-2.2.1'.
Perhaps you need to add `mtl' to the build-depends in your .cabal file.
Use -v to see a list of the files searched for.
```

**Comment by LukaHorvat** [comment]
Further investigation: I've tried with a different package. Adding `import Text.Parsec` gave me a message about an unknown module. Then I added parsec to `build-depends` and the message changed to the "member of a hidden package" one.
Meaning there's a difference between a package that isn't installed and one that's somehow "hidden".

**Comment by lierdakil** [comment]
Could you check if this is related to ide-haskell environment, or is pure ghc-mod issue? I.e. run `ghc-mod check Main.hs` (replace `Main.hs` with existing source file path) in project directory.

**Comment by LukaHorvat** [comment]
You're right. It is a `ghc-mod` thing. I guess this closes the issue. I need to fix my `ghc-mod`.

**Comment by lierdakil** [comment]
Okay, what version of ghc-mod, ghc and cabal do you use? Usually, `cabal clean && cabal configure && cabal build` should fix any problems of this sort, but there might be something else.

**Comment by LukaHorvat** [comment]
That seemed to solve it, although it might have also been the pull request mentioned here https://github.com/kazu-yamamoto/ghc-mod/issues/511
