### ISSUE TITLE
ide-haskell can't see haskell-ghc-mod installed: yellow warring pops up

### ISSUE THREAD

**Issue by emcek** [atom-haskell/ide-haskell#88]
![image](https://cloud.githubusercontent.com/assets/475312/8874184/bd667260-320e-11e5-97b9-fbfee9021f01.png)
also 'Use backend' drop down list in setting is empty and can't not choose any backend

**Comment by emcek** [comment]
reinstall of ide-haskel and haskell-ghc-mod helped. Now is working.

**Comment by lierdakil** [comment]
Something certainly went wrong there: `undefined` version is clearly not something I would expect...

**Comment by lierdakil** [comment]
You might want to reinstall all such "strange" packages.

**Comment by emcek** [comment]
Yes, I noticed it later.
