### ISSUE TITLE
Autocomplete not working with gloss

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell#89]
What conditions are required to get autocompletion for a package?

I've installed gloss in my sandbox, it's in my build.depends, the project is configured and works fine. I've run `cabal clean && cabal configure` and I've done a fress reinstall of the sandbox. Everything works except autocompletion for gloss. 

![image](https://cloud.githubusercontent.com/assets/370627/8896103/9edbfc0e-33f1-11e5-8923-9ad6bdc652c2.png)

And when I add the import, I don't get completion for it's functions. The module works just fine otherwise (errors and everything).

**Comment by lierdakil** [comment]
Module list is acquired from `ghc-mod list` command. If gloss doesn't show up in there, I'm not sure what I can do about that. Bear in mind that symbol suggestion database is built using `ghc-mod browse`.
