### ISSUE TITLE
"Show type" calculates incorrect position

### ISSUE THREAD

**Issue by torgeirsh** [atom-haskell/ide-haskell#92]
Tab characters seem to be treated as one character instead of eight when the cursor position to send to ghc-mod is calculated. Usually the wrong type is shown as a result.

**Comment by lierdakil** [comment]
I understand that it's not my place to tell you anything about your formatting conventions, but I'd suggest using soft tabs if at all possible. Since I use Atom's facilities to determine buffer position, it's not likely I will be able to do something about this to a satisfactory degree. You might try filing an issue with https://github.com/atom/atom repo, but I'm not sure what their response would be. Sorry I can't be of immediate help.

**Comment by torgeirsh** [comment]
Thanks, but it's not by accident that I use tabs. :) What are these facilities called? Is it a function or method call or something similar? I'd like to include the name when I report the issue upstream.

**Comment by lierdakil** [comment]
Well, everything in `TextEditor` that deals with buffer position seems to be affected. In simplest case that would be `TextEditor.getCursorBufferPosition()` and `TextEditor.markBufferRange()`

**Comment by lierdakil** [comment]
By far simplest way to showcase this issue is looking at status bar, where cursor position is displayed: if soft tabs are disabled, then tab character shifts this counter by 1 instead of 8 or whatever is configured.

**Comment by torgeirsh** [comment]
I don't know if what they say about screen coordinates in the referenced upstream issue makes any sense? It does seem like it would cause trouble with different tab settings and e.g. word wrap. Perhaps it's best to iterate the line and bump the horizontal position by 8 instead of 1 whenever there is a tab, as that's specifically what Haskell compilers expect, regardless of editor settings?

**Comment by lierdakil** [comment]
I guess you have a point there, although this seems weird to me. Then again, tabs always seem weird to me, so that's nothing new. I think I have a terrible idea, that just might work. Let me try it.

**Comment by lierdakil** [comment]
Try v0.8.11, with any luck it should work for you. Report back in any case, please.

**Comment by torgeirsh** [comment]
Thanks for the effort, but unfortunately no luck. haskell-ghc-mod 0.8.11 behaves just like before, i.e. on a line indented with one tab I have to place the cursor 7 positions too far to the right for "show type" to show the correct type.

**Comment by lierdakil** [comment]
Does it at least highlight correctly?

**Comment by lierdakil** [comment]
K, I found a problem (not necessarily the problem). Please check 0.8.12 -- it should at least somewhat work (I checked, albeit not as thoroughly as I probably should've).

**Comment by torgeirsh** [comment]
Great, now it appears to work! Thanks

**Comment by lierdakil** [comment]
Had to revert my changes for this for now, because it was causing massive problems. This needs more thought apparently. I will try to tackle this from another angle sometime this week. Sorry for any inconvenience this might cause you.
