### ISSUE TITLE
Atom still failing with ghc-mod  version 5.3.0.0 compiled by GHC 7.10.2

### ISSUE THREAD

**Issue by schrepfler** [atom-haskell/ide-haskell#94]
The ghc-mod project released a new version of their library but it seems it still has issues. This is the alert that I'm getting when I perform Haskell IDE > Check

Haskell-ghc-mod: /Users/schrepfler/Library/Haskell/bin/ghc-mod check /Users/schrepfler/IdeaProjects/memegen/src/Main.hs failed with error code 1
cabal-helper-wrapper: Installing a private copy of Cabal because we couldn't
find the right version in your global/user package-db, this might take a
while but will only happen once per Cabal version you're using.
If anything goes horribly wrong just delete this directory and try again:
    /Users/schrepfler/.ghc-mod/cabal-helper
If you want to avoid this automatic installation altogether install
version 1.16.0 of Cabal manually (into your user or global package-db):
    $ cabal install Cabal --constraint "Cabal == 1.16.0"
Installing Cabal 1.16.0 ...
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: Cabal (user goal)
rejecting: Cabal-1.22.4.0/installed-435..., 1.22.4.0, 1.22.3.0, 1.22.2.0,
1.22.1.1, 1.22.1.0, 1.22.0.0, 1.20.0.3, 1.20.0.2, 1.20.0.1, 1.20.0.0,
1.18.1.6, 1.18.1.5, 1.18.1.4, 1.18.1.3, 1.18.1.2, 1.18.1.1, 1.18.1, 1.18.0,
1.16.0.3, 1.16.0.2, 1.16.0.1 (global constraint requires ==1.16.0)
trying: Cabal-1.16.0
trying: base-4.8.1.0/installed-075... (dependency of Cabal-1.16.0)
next goal: unix (dependency of Cabal-1.16.0)
rejecting: unix-2.7.1.0/installed-750..., 2.7.1.0, 2.7.0.1, 2.7.0.0 (conflict:
Cabal => unix>=2.0 && <2.7)
rejecting: unix-2.6.0.1, 2.6.0.0 (conflict: base==4.8.1.0/installed-075...,
unix => base>=4.5 && <4.7)
rejecting: unix-2.5.1.1, 2.5.1.0 (conflict: base==4.8.1.0/installed-075...,
unix => base>=4.5 && <4.6)
rejecting: unix-2.5.0.0 (conflict: base==4.8.1.0/installed-075..., unix =>
base>=4.2 && <4.5)
rejecting: unix-2.4.2.0, 2.4.1.0 (conflict: base==4.8.1.0/installed-075...,
unix => base>=4.2 && <4.4)
rejecting: unix-2.4.0.2, 2.4.0.1 (conflict: base==4.8.1.0/installed-075...,
unix => base>=4.2 && <4.3)
rejecting: unix-2.4.0.0 (conflict: base==4.8.1.0/installed-075..., unix =>
base>=4.1 && <4.3)
rejecting: unix-2.3.2.0, 2.3.1.0, 2.3.0.0, 2.2.0.0, 2.0 (conflict:
base==4.8.1.0/installed-075..., unix => base<4.3)
Dependency tree exhaustively searched.
cabal-helper-wrapper: Installing Cabal version 1.16.0 failed.
You have the following choices to fix this:
- The easiest way to try and fix this is just reconfigure the project and try
  again:
        $ cabal clean && cabal configure
- If that fails you can try to install the version of Cabal mentioned above
  into your global/user package-db somehow, you'll probably have to fix
  something otherwise it wouldn't have failed above:
        $ cabal install Cabal --constraint 'Cabal == 1.16.0'
- If you're using `Build-Type: Simple`:
  - You can see if you can reinstall your cabal-install executable while
    having it linked to a version of Cabal that's available in you
    package-dbs or can be built automatically:
        $ ghc-pkg list | grep Cabal  # find an available Cabal version
            Cabal-W.X.Y.Z
        $ cabal install cabal-install --constraint 'Cabal == W.X.*'
    Afterwards you'll have to reconfigure your project:
        $ cabal clean && cabal configure
- If you're using `Build-Type: Custom`:
  - Have cabal-install rebuild your Setup.hs executable with a version of the
    Cabal library that you have available in your global/user package-db:
        $ cabal clean && cabal configure
    You might also have to install some version of the Cabal to do this:
        $ cabal install Cabal
ghc-mod: readCreateProcess: /Users/schrepfler/Library/Haskell/libexec/cabal-helper-wrapper "/Users/schrepfler/IdeaProjects/memegen" "/Users/schrepfler/IdeaProjects/memegen/dist" "package-db-stack" "entrypoints" "source-dirs" "ghc-options" "ghc-src-options" "ghc-pkg-options" "ghc-merged-pkg-options" "ghc-lang-options" "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" (exit 1): failed

**Comment by lierdakil** [comment]
In short, ghc-mod 5.3.0.0 is a bit broken in general and with ide-haskell in particular. Please wait for 5.1, which will hopefully work.

Note that first run on new ghc/cabal configuration will fail until cabal-helper does its thing (which can take a couple minutes)

**Comment by lierdakil** [comment]
Closing since ghc-mod 5.4 is out.
