### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by filmackay** [atom-haskell/ide-haskell#95]
Installed packages:
```
autocomplete-haskell
gist-it
haskell-ghc-mod
haskell-hoogle
ide-haskell
language-haskell
minimap
select-rectangle
```
Sample code
```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}

module Test
where

import Prelude
import Language.Haskell.TH.Syntax
import Language.Haskell.TH.Lib
import Control.Monad

unNest n = do
    vs <- replicateM n (newName "x")
    lamE [foldr (\a b -> tupP [varP a , b])
                (conP '() [])
                vs]
         (tupE (map varE vs))
```
A warning complaining about the ```(conP '() [])``` line appears, which does not appear from running ghc-mod manually: ```Parse error )```. This warning disappears when disabling ide-haskell.

Other details:
OS: OSX 10.10.4
ghc-mod version 0 compiled by GHC 7.10.1 (from https://github.com/ghcformacosx/ghc-dot-app/releases/download/v7.10.1-r0/ghc-7.10.1-r0.zip)

**Comment by lierdakil** [comment]
Okay, what I can say right now is it's `hlint` that complains about this code, not `ghc-mod`. As for why exactly is a mystery to me.

**Comment by lierdakil** [comment]
Okay. Sorry for bouncing you around, but it seems very much like hlint issue (which is used internally by ghc-mod). You can disable 'On Save Lint' option in ide-haskell settings to deal with visual annoyance. As for issue itself, I can only suggest taking this up with upstream at https://github.com/ndmitchell/hlint/issues
If you want, I can pass it to them instead. If you prefer this option, please run `hlint --version` and post its output here, if it's not too much trouble. Thanks.

**Comment by mpickering** [comment]
I opened an issue to deal with this. https://github.com/haskell-suite/haskell-src-exts/issues/274

**Comment by lierdakil** [comment]
Fixed in upstream.
